cider/exec/module/batch/CiderArrowBufferHolder.cpp, cider/exec/module/batch/CiderArrowBufferHolder.h, cider/exec/module/batch/CiderBatch.cpp, cider/exec/module/batch/CiderBatchUtils.cpp, cider/exec/operator/aggregate/CiderAggTargetColExtractor.h, cider/exec/operator/aggregate/CiderAggTargetColExtractorTmpl.h, cider/include/cider/batch/CiderBatch.h, cider/include/cider/batch/ScalarBatch.h, cider/include/cider/batch/StructBatch.h, cider/tests/CiderAggTestHelper.h, cider/tests/CiderArrowBatchTest.cpp, cider/tests/CiderNongroupbyAggTestHelper.h
Change null allocation procedure in new CiderBatch.
To make the null allocation in CiderBatch on demand.
- ```resizeBatch``` will not (re-)allocate nulls automatically unless the nulls exists.
- ```getMutableNulls``` will has a side effect to allocate nulls.
UTs
Infra
Pls take a review. @jikunshang @xieqi @winningsix
=> [POAE7-2335] CiderBatch Refactor for Better Null Allocation

cider/exec/operator/aggregate/CiderAggTargetColExtractorBuilder.cpp, cider/exec/operator/aggregate/CiderAggTargetColExtractorBuilder.h, cider/exec/operator/aggregate/CiderAggTargetColExtractorTmpl.h
+ under condition: using new data format
+ use value instead of null buffer when fetching result 
+ under condition: using new data format
+ value in count result include null information.(0 represent null)
+ so null buffer will not be set during process
No
UTs
=> [POAE7-2347] optimize agg count extractor

cider/tests/functionality/CiderStringTest.cpp, cider/tests/utils/QueryDataGenerator.h
Incorrect filter result because of null varchar and len 0 varchar.
The duckdb will regard len 0 varchar as null but query data generator will not, so the UT will fail if random generated varchar's length is 0 
Fix bug
NO
Change the min length of random varchar to 0 in CiderStringTest.cpp, so the bug can happen again. After the fix the UT can all pass.
bug
=> [POAE7-2385]incorrect filter result because of null varchar and len 0 varchar

cider-velox/src/CiderOperator.cpp, cider-velox/test/AggWithRandomDataTest.cpp, cider/exec/module/CiderCompilationResultImpl.h, cider/exec/module/CiderCompileModule.cpp, cider/exec/module/CiderRuntimeModule.cpp, cider/exec/plan/parser/SubstraitToRelAlgExecutionUnit.cpp, cider/exec/plan/parser/SubstraitToRelAlgExecutionUnit.h, cider/include/cider/CiderCompileModule.h, cider/tests/CiderAggTestHelper.h, cider/tests/CiderNongroupbyAggTestHelper.h, cider/tests/CiderRuntimeModuleTest.cpp, cider/tests/CompileWorkUnitTest.cpp, cider/tests/Substrait2IRTest.cpp, cider/tests/utils/CiderBenchmarkRunner.cpp, cider/tests/utils/CiderQueryRunner.cpp, cider/tests/utils/QueryDataGenerator.h, docs/CiderAllocator-use-guide.rst
changed the CiderTableSchema varable from class  to shared_ptr in CiderCompilationResults and the rst file format adjustment
we found that create CiderTableSchema object multiple times in CiderRuntimeModule code , will cause many memory allocations，so we changed it to shared_ptr
No
UTs
codeRefactor
=> [POAE7-2384] change CiderTableSchema to shared_ptr in CiderCompilationResults

cider/function/substrait/CMakeLists.txt, cider/function/substrait/SubstraitFunctionLookup.cpp, cider/function/substrait/SubstraitSignature.cpp, cider/tests/utils/CiderQueryRunner.h
folly is not used by debug model in function look up, that will cause compilation failure, fix that use cider util split replace folly:split
folly is not used by debug model in function look up, that will cause compilation failure, fix that use cider util split replace folly:split
No
Uts
BUG
=> [POAE7-2408] Replace folly::split of function look up

cider-velox/src/ArrowDataConvertor.cpp, cider-velox/src/RawDataConvertor.cpp, cider-velox/src/TypeConversions.h, cider-velox/test/AggWithRandomDataTest.cpp, cider/exec/module/CiderRuntimeModule.cpp, cider/include/cider/CiderTableSchema.h, cider/tests/utils/DuckDbQueryRunner.cpp, cider/util/measure.h
Modify the Substrait::Type pass by reference instead of pass by object, and change the string to char* in measure.h 
During code refactor with CiderAllocator and memory analysis，we found that in function CiderRuntimeModule::fetchResults, the CiderTableSchema->Substrait::Type occupies too much memory, so we try to optimize the memory usage of Substrait::Type
also in measure.h->InjectTime to save memory usage.
No
UTs
codeRefactor
=> [POAE7-2404] Modify the Substrait::Type pass by reference

cider/tests/functionality/CiderStringTest.cpp, cider/tests/substrait_plan_files/in_string_nest_with_binop.json
Add a UT to cover substr wrapped with binop outside
a bug for tpc-h q22 but found code fix in recent PR, so add a UT instead
No
UT
=> [POAE7-2402] add test case for substr wrapped with BinOp outside

cider/exec/module/CiderRuntimeModule.cpp, cider/tests/CiderLogTest.cpp, cider/util/Logger.cpp, cider/util/Logger.h
Previous memory allocation of output old CiderBatch doesn't follow the schema in CiderOutputTableSchema or CiderAggHashTable, which works fine when the size of item less than 8 bytes. However, the size of VarChar type recently supported is 16 bytes, it leads memory problems.
No
UTs and e2e test.
BugFix
Pls take a review @harborn @winningsix
=> [POAE7-2432] Fix Old CiderBatch Memory Allocation for Group-By Result Fetching

cider/tests/utils/DuckDbQueryRunner.cpp, cider/tests/utils/DuckDbQueryRunner.h, cider/tests/utils/DuckDbQueryRunnerTest.cpp
Updated `DuckDbResultConvertor` to support `ArrowArray` and `ArrowSchema`. Currently supports *primitive scalar types*.
1. In `DuckDbResultConvertor`: Added `fetchDataToArrowFormattedCiderBatch` method. The API use case is the same as the existing `fetchDataToCiderBatch`, but it returns `CiderBatch` instances that uses Arrow format as underlying memory layout.
2. In `DuckDbQueryRunnerTest.cpp`: Added simple handcrafted tests on new convertor API for primitive types (`int` / `float` / `double` / `bool`), along with util functions to run these tests. Newly added tests are put under `DuckDBResultConvertorTest`.
- Unit tests here are subject to change. They will be updated when `CiderBatchChecker` are updated to support Arrow format.
These changes are part of the changes needed to migrate …
=> [POAE7-2400] DuckDB output to Arrow-format CiderBatch

cider-velox/src/CiderJoinBuild.cpp, cider-velox/src/CiderJoinBuild.h, cider-velox/src/CiderOperator.cpp, cider-velox/src/CiderOperator.h, cider-velox/test/CiderOperatorJoinTest.cpp
convert multi batches to a single RowVector then convert to CiderBatch for hash join build
Remove previous hard code
No
UT
veloxIntegration
=> [POAE7-2316] Convert vector<VectorPtr> to CiderBatch

cider/exec/module/CiderOptions.cpp, cider/exec/template/CompilationOptions.h, cider/exec/template/NativeCodegen.cpp, cider/include/cider/CiderOptions.h, cider/tests/CMakeLists.txt, cider/tests/Sql2IR.cpp, docs/develop.rst, docs/develop/utils.rst
add a tool to dump substrait plan, llvm ir and llvm cfg
the tool can help to understand code
No
UTs
INFRA
=> [POAE7-2455] Add a tool to dump substrait plan, llvm ir and llvm cfg

cider-velox/src/ciderTransformer/CiderPlanUtil.cpp, cider-velox/src/planTransformer/PlanBranches.h, cider-velox/src/planTransformer/PlanUtil.h
Change CiderPlanRewriter to support multi-source node rewriting.
As V2S convertor Join support is done, change the CiderPlanRewriter to use the convertor and rewrite join pattern into  CiderPlanNode.
No.
Will be tested as a part of Join-related tests.
velox-plugin
=> [POAE7-2308] Transformer support multi-source Cider plan

cider/tests/functionality/CiderFilterTest.cpp, cider/tests/utils/CiderTestBase.cpp, cider/tests/utils/CiderTestBase.h, cider/tests/utils/DuckDbQueryRunner.cpp, cider/tests/utils/QueryArrowDataGenerator.h
Some fixes and improvements to make it an easier way to use new Arrow Format including data generator and checker.
1. Fix empty result arrow batch core dump.
2. Fix compile error when using both data generator.
3. Fix and use `checkArrowEq` in `assertQueryArrow`.
4. Fix arrow format in `SetUp` of `CiderTestBase`.
5. Add and enable tests for null and not null.
fix & improvements.
No.
UTs.
=> [POAE7-2417] Support NotNull Ops for Arrow Format and some fix

cider/exec/module/batch/CiderArrowBufferHolder.cpp, cider/exec/module/batch/CiderArrowBufferHolder.h, cider/exec/module/batch/CiderBatch.cpp, cider/exec/module/batch/CiderBatchUtils.cpp, cider/exec/plan/parser/TypeUtils.h, cider/exec/template/CodeGenerator.h, cider/exec/template/Codec.cpp, cider/exec/template/Codec.h, cider/exec/template/CodegenColValues.h, cider/exec/template/ColumnIR.cpp, cider/exec/template/CompareIR.cpp, cider/exec/template/IRCodegen.cpp, cider/exec/template/TargetExprBuilder.cpp, cider/exec/template/operator/aggregate/CiderAggregateCodeGenerator.cpp, cider/exec/template/operator/aggregate/CiderAggregateCodeGenerator.h, cider/function/aggregate/CiderRuntimeFunctions.h, cider/function/scalar/DecodersImpl.h, cider/function/scalar/RuntimeFunctions.cpp, cider/include/cider/batch/CiderBatch.h, cider/include/cider/batch/ScalarBatch.h, cider/tests/CiderArrowBatchTest.cpp, cider/tests/functionality/CiderStringTest.cpp, cider/tests/utils/CiderTestBase.cpp, cider/tests/utils/CiderTestBase.h
1. define and impl ScalarBatch<CiderVarchar>
2. impl string project/ cmp function with arrow data format, could pass simple uts.
3. fix some typos.
todo:
1. migrate to arrow based test framework when utils ready. (string builder, duck convertor).
No
UT.
generated IR (row function part)
project string column:
```
; Function Attrs: alwaysinline
define i32 @row_func(i64* %group_by_buff, i64* %varlen_output_buff, i32* %crt_matched, i32* %total_matched, i32* %old_total_matched, i32 %max_matched, i64* %agg_init_val, i64 %pos, i64* %frag_row_off, i64* %num_rows_per_scan, i8* %literals, i8* %col_buf0, i8* %col_buf1, i64* %join_hash_tables) #25 {
entry:
br i1 true, label %filter_true, label %filter_false
filter_true:                                      ; preds = %entry
%0 = load i32, i32* …
```
=> [POAE7-2415] codegen string using Arrow format

cider/exec/module/batch/CiderBatch.cpp, cider/exec/module/batch/CiderBatchUtils.cpp, cider/include/cider/batch/CiderBatch.h, cider/tests/utils/CMakeLists.txt, cider/tests/utils/CiderBatchChecker.cpp, cider/tests/utils/CiderBatchStringifier.cpp, cider/tests/utils/CiderBatchStringifier.h, cider/tests/utils/CiderInt128.cpp, cider/tests/utils/CiderInt128.h, cider/tests/utils/CiderInt128Test.cpp, cider/tests/utils/DuckDbArrowAdaptor.cpp, cider/tests/utils/DuckDbQueryRunner.cpp, cider/tests/utils/DuckDbQueryRunnerTest.cpp
Updated `DuckDbQueryRunner` and `CiderBatchChecker` to support 128-bit decimal types exported by DuckDb, including `HUGEINT` and `DECIMAL(a, b)` types (both stored as 128-bit integers in Arrow Array).
Both types are stored as 128-bit (16 byte) binaries in the exported array. For `HUGEINT`, we interpret it as an `int128` value, and compare to the `int64 ` value in Cider (we assume no overflow will occur in `int64`). For `DECIMAL`, we convert it to `double` and compare with the `double`values in Cider. Both comparisons are based on `ConcatenatedRow`s because direct `memcmp` will always fail as the size of arrow arrays are different.
NOTE: Current implementation is based on GCC's support for `__int128_t` types, and it may require GCC/Clang compilers to work properly.
For supporting UTs that …
=> [POAE7-2509] UT framework support for 128-bit DECIMALs

cider/exec/module/batch/CiderBatchUtils.cpp, cider/tests/utils/CiderBatchChecker.cpp, cider/tests/utils/CiderBatchChecker.h, cider/tests/utils/CiderBatchCheckerTest.cpp, cider/tests/utils/CiderBatchStringifier.cpp, cider/tests/utils/CiderBatchStringifier.h, cider/tests/utils/DuckDbQueryRunner.cpp, cider/tests/utils/DuckDbQueryRunnerTest.cpp, cider/tests/utils/QueryArrowDataGenerator.h, cider/tests/utils/Utils.h
- Updated `DuckDbQueryRunner` and `CiderBatchChecker` support for arrow-formatted UTF-8 char sequences.
- Supports inserting/fetching string arrow arrays into/from DuckDb databases
- Supports checking validity, offset and data buffer of UTF-8 arrow arrays
- Fixed STRING/VARCHAR compatibility issues in `QueryArrowDataGenerator`
- Renamed helper class `ArrowToCiderBatch` to `ArrowBuilderUtils` in `Utils.h`
Part of UT framework migration to arrow format.
No
Unit tests.
=> [POAE7-2470] Arrow STRING/VARCHAR support for DuckDb runner & CiderBatchChecker

cider-velox/src/CiderJoinBuild.cpp, cider-velox/src/CiderJoinBuild.h, cider-velox/src/CiderOperator.cpp, cider-velox/src/CiderOperator.h, cider-velox/test/CiderOperatorHashJoinTest.cpp
Make CiderJoinBridge to deliver CiderBatch.
Upstream op will destroy CiderBatch after it closed which may cause memory issue for downstream op.
No
Existing UT. 
veloxIntegration
=> [POAE7-2479] Use CiderBatch as data type for join bridge to bypass existing Velox memory ownership mechnism

cider/exec/nextgen/jitlib/base/JITValue.h, cider/exec/nextgen/jitlib/base/JITValueOperations.h, cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp, cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.h, cider/tests/nextgen/jitlib/JITLibTest.cpp
add JITValue Compare and Logical Operations like ==,!=,&&,||, >,<, <=,>=
Add UTs about the added operations 
Support the next gen framework
No.
UTs.
INFRA
=> [POAE7-2528] JITValue Compare and Logical Operations Support

cider/exec/operator/aggregate/CiderAggTargetColExtractorTmpl.h
Fix conflicts with the merged PR [[POAE7-2490] String op support for arrow format](https://github.com/intel/BDTK/pull/129), that didn't expose on previous CI.
fix
No.
UTs.
=> [POAE7-2531] [HOTFIX] Fix conflicts with POAE7-2490

cider/exec/module/CiderRuntimeModule.cpp, cider/exec/module/batch/CiderBatchUtils.cpp, cider/include/cider/CiderTableSchema.h, cider/tests/functionality/CiderAggArrowTest.cpp, cider/tests/substrait_plan_files/avg_all_null_partial.json, cider/tests/substrait_plan_files/avg_with_null_partial.json, cider/tests/substrait_plan_files/multi_fp_avg_partial.json, cider/tests/utils/CiderTestBase.cpp, cider/tests/utils/CiderTestBase.h
1. verify PartialAVG in CiderAggArrowTest for arrow format.
2. fix bug that SUM in PartialAVG return null value, when all inputs are null(should be 0).
3. support struct for ciderbatch to arrowarray convertor and add *getFlattenColNames* method for CiderTableSchema
NO
CiderAggArrowTest
=> [POAE7-2574] verify PartialAVG for arrow format

cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp, cider/function/string/StringOps.cpp, cider/tests/functionality/CiderStringTest.cpp, cider/tests/substrait_plan_files/stringop_ltrim_1.json, cider/tests/substrait_plan_files/stringop_ltrim_2.json, cider/tests/substrait_plan_files/stringop_ltrim_literal.json, cider/tests/substrait_plan_files/stringop_ltrim_nested_1.json, cider/tests/substrait_plan_files/stringop_ltrim_nested_2.json, cider/tests/substrait_plan_files/stringop_rtrim_1.json, cider/tests/substrait_plan_files/stringop_rtrim_2.json, cider/tests/substrait_plan_files/stringop_rtrim_literal.json, cider/tests/substrait_plan_files/stringop_rtrim_nested_1.json, cider/tests/substrait_plan_files/stringop_rtrim_nested_2.json, cider/tests/substrait_plan_files/stringop_trim_1.json, cider/tests/substrait_plan_files/stringop_trim_2.json, cider/tests/substrait_plan_files/stringop_trim_literal.json, cider/tests/substrait_plan_files/stringop_trim_literal_1.json, cider/tests/substrait_plan_files/stringop_trim_literal_2.json, cider/tests/substrait_plan_files/stringop_trim_literal_3.json, cider/tests/substrait_plan_files/stringop_trim_nested_1.json, cider/tests/substrait_plan_files/stringop_trim_nested_2.json, cider/type/plan/Analyzer.cpp, cider/type/plan/Analyzer.h
Arrow format support for scalar function TRIM (String Op) and its variants (LTRIM/RTRIM).
1. Enabled existing code for TRIM plan nodes to EU conversion.
2. Added patches for TRIM ops.
3. Added tests for TRIM/LTRIM/RTRIM. Substrait plans for TRIM UTs are currently **manually created** because modifying substrait-java to support conversion of TRIM ops is a bit nontrivial.
4. Fixed bug in `Trim::operator()` when dealing with RTRIM. It erroneously retained 1 char in cases where all characters should be trimmed (e.g. `RTRIM('xxxxx', 'x')` returns `'x'` instead of `''`).
Arrow format migration.
No.
UTs.
=> [POAE7-2559] Scalar Function String Op: TRIM

ci/scripts/intel_copyright_files.txt, cider/exec/plan/parser/SubstraitToRelAlgExecutionUnit.h, cider/exec/plan/validator/CMakeLists.txt, cider/exec/plan/validator/CiderPlanValidator.cpp, cider/exec/plan/validator/CiderPlanValidator.h, cider/exec/plan/validator/SingleNodeValidator.cpp, cider/exec/plan/validator/SingleNodeValidator.h, cider/tests/plan/CMakeLists.txt, cider/tests/plan/CiderPlanValidatorTest.cpp, cider/tests/substrait_plan_files/cider_plan_validator_join.json
Add plan validator module for cider, with single plan node validation as first step
provide plan validation capability for Cider
Yes.
Public APIs:
static bool isSupported(const substrait::Plan& plan, const std::string& from_platform);
static PlanSlice getCiderSupportedSlice(substrait::Plan& plan, std::string& from_platform);
UT
=> [POAE7-2540] PlanNode validation for cider plan validator

cider/exec/nextgen/Context.h, cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.cpp, cider/exec/nextgen/operators/ArrowSourceNode.cpp, cider/exec/nextgen/operators/ArrowSourceNode.h, cider/exec/nextgen/operators/CMakeLists.txt, cider/exec/nextgen/operators/ColumnToRowNode.cpp, cider/exec/nextgen/operators/ColumnToRowNode.h, cider/exec/nextgen/operators/FilterNode.cpp, cider/exec/nextgen/operators/SourceNode.cpp, cider/exec/nextgen/operators/SourceNode.h, cider/exec/nextgen/parsers/RelAlgEUParser.cpp, cider/function/scalar/RuntimeFunctions.cpp, cider/function/scalar/RuntimeFunctions.h, cider/tests/nextgen/compiler/NextgenCompilerTest.cpp, cider/tests/nextgen/operator/CMakeLists.txt, cider/tests/nextgen/operator/ColumnToRowTest.cpp, cider/tests/nextgen/operator/MockRowToColumn.h, cider/type/plan/Expr.h
- Add SourceNode and SourceTranslator, get data buffer and null buffer from ArrowArray
- Add C2RNode and C2RTranslator, make buffer decoder column to row
- Add test file about SourceTranslator and C2RTranslator, Construct an ArrowArray and pass it in, pass the source->column2row->filter->project->sink workflow to verify correctness
For Next Gen Framework support
No
UTs
INFRA
=> [POAE7-2586] Source and ColumnToRow Translator support

cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp, cider/exec/template/ExpressionRewrite.cpp, cider/tests/functionality/CiderStringTest.cpp, cider/tests/substrait_plan_files/stringop_concat_filter.json, cider/tests/substrait_plan_files/stringop_concat_filter_null.json, cider/tests/substrait_plan_files/stringop_trim_nested_3.json, cider/tests/substrait_plan_files/stringop_upper_nested_1.json, cider/tests/substrait_plan_files/stringop_upper_nested_2.json, cider/type/plan/Analyzer.cpp, cider/type/plan/Analyzer.h, cider/util/sqldefs.h
Added support for string concatenation ops (`col_1 || 'blah'`, which means `CONCAT(col_1, 'blah')`).
1. Added support for concatenating literals with literals (`literal || literal`) and literals with variables (`literal || column`). Note that currently concatenating two columns is not supported.
2. substrait-java only recognizes the `||` operator as string concatenation, and does not support parsing `CONCAT` function. So all test cases used `||` operator.
3. Fixed bug in nested stringop expression folding. When a nested stringop exists in a `WHERE` clause, inner stringops will be accidentally folded and dropped. Check the notes in the source code for details.
4. Added more complicated nested stringop test cases.
Adding stringop features.
No.
UT.
=> [POAE7-2560] Scalar function support: string concatenation

cider/exec/nextgen/operators/RowToColumnNode.cpp, cider/exec/nextgen/parsers/RelAlgEUParser.cpp, cider/tests/nextgen/functional/CMakeLists.txt, cider/tests/nextgen/functional/CiderUOperNextgenTest.cpp, cider/type/plan/Analyzer.cpp, cider/type/plan/Analyzer.h, cider/type/plan/CMakeLists.txt, cider/type/plan/UnaryExpr.cpp, cider/type/plan/UnaryExpr.h
move UOper out of Analyzer.h/Analyzer.cpp and support ISNULL/ISNOTNULL in UOper
expr codegen based on nextgen
No
UT
=> [POAE7-2623] support ISNULL/ISNOTNULL in nextgen

cider/exec/nextgen/jitlib/base/JITValue.h, cider/exec/nextgen/jitlib/base/JITValueOperations.h, cider/exec/nextgen/operators/FilterNode.cpp, cider/exec/nextgen/utils/JITExprValue.h, cider/tests/nextgen/compiler/CMakeLists.txt, cider/tests/nextgen/compiler/FilterProjectTest.cpp, cider/type/plan/BinaryExpr.cpp, cider/type/plan/BinaryExpr.h, cider/type/plan/ConstantExpr.cpp
support null in filter and expr
disable implicit cast for bool for some operator overload.
next-gen compiler
No
UT
INFRA
=> [POAE7-2648] support null in filter and expr

cider/exec/nextgen/jitlib/base/JITValueOperations.h, cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp, cider/exec/nextgen/operators/ArrowSourceNode.cpp, cider/exec/nextgen/operators/ColumnToRowNode.cpp, cider/exec/nextgen/operators/FilterNode.cpp, cider/exec/nextgen/operators/RowToColumnNode.cpp, cider/exec/nextgen/utils/JITExprValue.h, cider/tests/nextgen/compiler/FilterProjectTest.cpp, cider/type/plan/BinaryExpr.cpp, cider/type/plan/ConstantExpr.cpp
constant bool specialization in expr codegen.  
we should always fill null(false for not null, ) in expr, please don't use nullptr, and then we can pipeline all conditions without checking `isNullable`.
we check the const bool value inner and generate optimized IR with less calculation.
better user API and performance.
No
UT
INFRA
=> [POAE7-2652]bool specialization in expr

cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp, cider/function/string/StringOps.cpp, cider/tests/functionality/CiderStringTest.cpp, cider/tests/substrait_plan_files/stringop_regexp_replace_all.json, cider/tests/substrait_plan_files/stringop_regexp_replace_capture.json, cider/tests/substrait_plan_files/stringop_regexp_replace_first.json, cider/tests/substrait_plan_files/stringop_regexp_replace_neg_occ.json, cider/tests/substrait_plan_files/stringop_regexp_replace_neg_pos.json, cider/tests/substrait_plan_files/stringop_regexp_replace_position.json, cider/tests/substrait_plan_files/stringop_regexp_replace_second.json, cider/tests/utils/Utils.h, cider/type/plan/Analyzer.cpp, cider/type/plan/Analyzer.h
Added support for regular expression function `REGEXP_REPLACE(input, pattern, replacement, position, occurrence)`, which replaces one or more substrings that match `pattern` in `input` with `replacement`.
The implementation is based on substrait specification on `regexp_replace`, which should generally be the same as the `regexp_replace` implemented in PrestoDb (but with additional features to specify `position` and `occurrence`)
- Enabled existing `regexp_replace` code in code base.
- Added unit tests that cover basic features specified by substrait.
- There are 3 optional arguments that controls case sensitivity, multi-line replacement and dot character (`'.'`) matching respectively. These 3 arguments are NOT supported for now for lack of support to parse optional arguments.
String op …
=> [POAE7-2561] String Scalar Function support: regexp_replace

cider/exec/nextgen/jitlib/base/JITFunction.h, cider/exec/nextgen/jitlib/base/JITValue.h, cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.cpp, cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.h, cider/tests/nextgen/jitlib/JITLibTest.cpp
- add JITFunction ```packJITValue(const std::string& name,  const uint64_t alignment, const std::vector<JITValuePointer>& vals)```. To generate IR code. Pass in multiple JITValuePointers, allocate a buffer and store JITValuePointers,  alignment is used as memory alignment here, finally return the buffer head address.
- add related unit test in JITLibTest
For Next Gen Framework translator development
For example : we need to pass mutiple exprs as hash join keys in HashJoinTranslator
No
UTs
INFRA
=> [POAE7-2666] Support for calling multiple JITValue methods

src/cider/exec/nextgen/context/RuntimeContext.h, src/cider/exec/nextgen/operators/RowToColumnNode.cpp, src/cider/tests/nextgen/functional/FilterTest.cpp, src/cider/tests/utils/CiderBatchChecker.cpp
1. add null_vector for non-nullable cols
2. fill null_count for output arrow array
3. port filter TCs
nextgen support
No
UT
=> [POAE7-2713] Enable and support filter TCs in nextgen

src/cider/exec/nextgen/operators/ColumnToRowNode.cpp, src/cider/tests/nextgen/compiler/FilterProjectTest.cpp
If an input query did not reference any column in the input table, e.g. `select 'a-string-literal' from test` or `select 2 from test`, a segmentation fault would occur during ColumnToRow codegen.
This is because, `ColumnToRowNode` gets input from preceding `ArrowSourceNode`. `ArrowSourceNode` keeps all columns that will be used in a vector `input_exprs_`. When inserting `ArrowSourceNode` into the OpNodePipeline, an `InputAnalyzer` will remove any column that is not used in the query (Around L71 in RelAlgEUParser.cpp). In the example queries above, no column is referenced, so all columns are erased from `input_exprs_`. As a result, `input_exprs_` is an *empty vector*.
However, the `ColumnToRowNode` attempts to access the first element in the `input_exprs_` in order to get the row number of …
=> [POAE7-2725] NextGen segfaults if no column is referenced in input query

src/cider/exec/nextgen/CMakeLists.txt, src/cider/exec/nextgen/context/CodegenContext.cpp, src/cider/exec/nextgen/context/CodegenContext.h, src/cider/exec/nextgen/context/RuntimeContext.cpp, src/cider/exec/nextgen/context/RuntimeContext.h, src/cider/tests/nextgen/compiler/ContextTest.cpp
- provide registerHashTable related function in codegenContext and setHashTable in RuntimeContext
- add related test file
- **(Since the design of the template class used by hashtable is not applicable this time, a hard-coded template class is now used, and the default template class will be provided later, and corresponding modifications will be made here)**
for NextGen FW and HashJoinTranslator development
No
UTs
INFRA
=> [POAE7-2679] CodegenContext Register Hashtable

src/cider/exec/nextgen/CMakeLists.txt, src/cider/exec/nextgen/Nextgen.cpp, src/cider/exec/nextgen/Nextgen.h, src/cider/exec/nextgen/context/Buffer.h, src/cider/exec/nextgen/context/CodegenContext.cpp, src/cider/exec/nextgen/context/CodegenContext.h, src/cider/exec/nextgen/context/RuntimeContext.cpp, src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp, src/cider/exec/nextgen/operators/CMakeLists.txt, src/cider/exec/nextgen/operators/ColumnToRowNode.cpp, src/cider/exec/nextgen/operators/HashJoinNode.cpp, src/cider/exec/nextgen/operators/HashJoinNode.h, src/cider/exec/nextgen/operators/OperatorRuntimeFunctions.h, src/cider/exec/nextgen/parsers/Parser.h, src/cider/exec/nextgen/parsers/RelAlgEUParser.cpp, src/cider/function/CMakeLists.txt, src/cider/tests/nextgen/compiler/CMakeLists.txt, src/cider/tests/nextgen/compiler/HashJoinTest.cpp, src/cider/type/plan/BinaryExpr.cpp
- Add HashJoinNode and Translator (inner hashjoin) and related RuntimeFuncitons, modify the parser to create HashJoinNode and add it to transform pipeline
- Add HashJoinTest, Construct a basic hash join sql to run the workflow to prove correctness
- Add null vector handling
- Refactor EU parser
- Change the createConstant using to createLiteral in some places
- Remove folly dependency
- Rebase hashtable  .h and .cpp file separation #304 
For HashJoin codegen in Next Gen FW design
No
UTs
INFRA
=> [POAE7-2665] HashJoinTranslator support 

src/cider/common/CMakeLists.txt, src/cider/common/hashtable/FixedHashMap.h, src/cider/common/hashtable/FixedHashTable.h, src/cider/common/hashtable/HashMap.h, src/cider/common/hashtable/HashSet.h, src/cider/common/hashtable/HashTable.h, src/cider/common/hashtable/HashTableKeyHolder.h, src/cider/common/interpreters/AggregationHashTable.cpp, src/cider/common/interpreters/AggregationHashTable.h, src/cider/exec/nextgen/context/CodegenContext.h, src/cider/tests/CMakeLists.txt, src/cider/tests/CiderNewAggHashTableTest.cpp, src/cider/tests/CiderNewHashTableTest.cpp
1. Add namespace `cider::hashtable` to all HashTable related classes.
2. Seperate all implementation parts of `AggregationHashTable.h` into `AggregationHashTable.cpp`. It can reduce compilation time and prevent redefinition errors.
3. Include `AggregationHashTable.h` in `CodegenContext.h` to expose compilation problems and prove it can be well used.
Improvement and integration.
No.
UTs.
=> [POAE7-2815] Add namespace and resolve redefinition with other modules for HashTable

cpp/src/cider/common/Arena.h, cpp/src/cider/common/base/unaligned.h, cpp/src/cider/common/hashtable/FixedHashSet.h, cpp/src/cider/common/hashtable/FixedHashTable.h, cpp/src/cider/common/hashtable/Hash.h, cpp/src/cider/common/hashtable/HashMap.h, cpp/src/cider/common/hashtable/HashSet.h, cpp/src/cider/common/hashtable/HashTable.h, cpp/src/cider/common/hashtable/HashTableAllocator.h, cpp/src/cider/common/interpreters/AggregationHashTable.cpp, cpp/src/cider/common/interpreters/AggregationHashTable.h, cpp/src/cider/tests/CMakeLists.txt
1. Now UTs fail due to conflicts between hash_table library and old codegen libraries. Move hash_table library out of global scope.
2. Revise TODOs.
3. Replace `cout` by `CiderException`.
Fix and improve.
No.
UTs.
=> [POAE7-2821] Fix uts and prevent conflict between hash_table and other libraries

cpp/src/cider-velox/benchmark/expression/ArithmeticAndComparison.cpp, cpp/src/cider/exec/module/CiderOptions.cpp, cpp/src/cider/exec/nextgen/Nextgen.cpp, cpp/src/cider/exec/nextgen/context/CodegenContext.h, cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.cpp, cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.cpp, cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp, cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.cpp, cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.h, cpp/src/cider/exec/nextgen/operators/OpNode.h, cpp/src/cider/exec/nextgen/operators/ProjectNode.cpp, cpp/src/cider/exec/nextgen/operators/ProjectNode.h, cpp/src/cider/exec/nextgen/operators/RowToColumnNode.cpp, cpp/src/cider/exec/nextgen/operators/RowToColumnNode.h, cpp/src/cider/exec/nextgen/transformer/Transformer.cpp, cpp/src/cider/exec/nextgen/utils/JITExprValue.h, cpp/src/cider/exec/plan/parser/TypeUtils.h, cpp/src/cider/exec/processor/DefaultBatchProcessor.cpp, cpp/src/cider/exec/processor/DefaultBatchProcessor.h, cpp/src/cider/function/scalar/RuntimeFunctions.cpp, cpp/src/cider/include/cider/CiderOptions.h, cpp/src/cider/type/plan/BinaryExpr.cpp, cpp/src/cider/type/plan/BinaryExpr.h, cpp/src/cider/type/plan/ColumnExpr.cpp, cpp/src/cider/type/plan/ColumnExpr.h, cpp/src/cider/type/plan/ConstantExpr.cpp, cpp/src/cider/type/plan/ConstantExpr.h, cpp/src/cider/type/plan/Expr.cpp, cpp/src/cider/type/plan/Expr.h, cpp/src/cider/util/CiderBitUtils.h
try to optimize expression performance
1) branchless null set and logic operation
2) xor replace not(and) for bit clear check
3) null separated for auto-vectorization
all optimization is under gflags, so nothing changed if all gflags are closed.
**branchless logic gain 15%~35% performance boost for logic operation**
**auto-vectorization will gain 2x performance boost, but null process is hard**
**this pr just enable auto-vectorization with null process splited, which hard to support keleene logic operation**
**so we propagate null, which is one strategy in arrow kernel**
some performance details on haswell:
```bash
============================================================================
/workspace/code/BDTK/src/cider-velox/benchmark/expression/ArithmeticAndComparison.cpprelative …
```
=> [POAE7-2809]try to optimize expression performance

cpp/src/cider/exec/nextgen/jitlib/base/ValueTypes.h, cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.cpp, cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITUtils.h, cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp, cpp/src/cider/tests/nextgen/jitlib/JITLibTest.cpp
arrow decimal type(int128) & base ops(math/cmp）support in jitlib level
Use llvm Int128 type to impl the underlying calculation of decimal type
complete steps including：
- Aligns the decimal points of lvalue and rvalue by adjusting to the same scale.
- **int128 basic ops**
- Place the right decimal point of the result value.
No
UTs
=> [POAE7-2797] jitlib decimal type(int128) support

cpp/src/cider/tests/utils/CiderArrowChecker.cpp
+ add new test for sum(int)
+ because sum(int) output in duckdb is decimal, which does not keep consistency with cider
+ refactor comparison part
+  encapsulate and reuse the section that handles null data 
+  extract function
+ pass test
No
UTs
INFRA
=> [POAE7-2860] Test framework support sum int and refactor comparison part

cpp/src/cider/exec/nextgen/operators/RowToColumnNode.cpp, cpp/src/cider/tests/nextgen/compiler/ArrayTest.cpp, cpp/src/cider/tests/nextgen/functional/CiderArrayTest.cpp, cpp/src/cider/tests/utils/ArrowArrayBuilder.h, cpp/src/cider/tests/utils/CiderArrowChecker.cpp, cpp/src/cider/tests/utils/CiderNextgenTestBase.h
1. Add UTs for arrow for primitive types.
2. Support array type for CiderArrowChecker.
No
CiderArrayTest.cpp
=> [POAE7-2856] Support Array in CiderNextgenTestBase

cpp/src/cider/exec/nextgen/context/CodegenContext.cpp, cpp/src/cider/exec/nextgen/context/CodegenContext.h, cpp/src/cider/exec/nextgen/context/ContextRuntimeFunctions.h, cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.cpp, cpp/src/cider/exec/nextgen/operators/QueryFuncInitializer.cpp, cpp/src/cider/exec/nextgen/utils/JITExprValue.h, cpp/src/cider/function/scalar/RuntimeFunctions.cpp, cpp/src/cider/tests/nextgen/functional/DictEncodingStringTest.cpp, cpp/src/cider/tests/nextgen/functional/StringTest.cpp, cpp/src/cider/tests/utils/DuckDbQueryRunner.cpp
Enable dictionary encoding string for nextgen query engine. 
In e2e test, velox will convert dictionary encoded row vector to dictionary encoded arrow array which are not supported in nextgen column reader before.
No
UT.
=> [POAE7-2849] Enable dictionary encoding string for nextgen query engine.

cpp/src/cider-velox/benchmark/expression/ArithmeticAndComparison.cpp, cpp/src/cider-velox/benchmark/expression/CMakeLists.txt, cpp/src/cider-velox/benchmark/expression/PipelineOperator.cpp, cpp/src/cider-velox/src/CiderPipelineOperator.cpp
PipelineOperator performance test against velox
and try to remove schema import which boost 7%
```bash
============================================================================
/workspace/code/BDTK/cpp/src/cider-velox/benchmark/expression/PipelineOperator.cpprelative  time/iter  iters/s
============================================================================
velox                                                        15.63s   63.96m
nextgen                                          130.69%     11.96s   83.59m
nextgenOpt                                       137.45%     11.38s   87.91m
```
performance test
No
no need
INFRA
=> [POAE7-2877]PipelineOperator performance test against velox

cpp/src/cider/common/hashtable/FixedHashMap.h, cpp/src/cider/common/hashtable/FixedJoinHashTable.h, cpp/src/cider/exec/operator/join/CiderJoinHashTable.cpp, cpp/src/cider/exec/operator/join/CiderJoinHashTable.h, cpp/src/cider/exec/operator/join/HashTableSelector.h
1. Integrate `JoinHashTable` with optimized `FixedHashMap` (aka `FixedJoinHashMap `), which supports Int8 and Int16 as join keys.
2. More test cases should be added after `JoinRel` can be well handled, meanwhile, add `JoinHashTable` selection algorithm. Currently, we assume that the input key type is always int32. 
Improvement.
No.
UTs.
=> [POAE7-2878] Add FixedJoinHashMap for Int8 and Int16 to JoinHashTable

cpp/src/cider/benchmarks/HashMapBenchmark.cpp, cpp/src/cider/common/hashtable/HashTable.h, cpp/src/cider/tests/CMakeLists.txt, cpp/src/cider/tests/CiderNewHashTableTest.cpp
1. Fix core dump when doing `resize()`.
2. Set default size of HashMap to 1 << 12.
3. Optimize HashTableBenchmark with larger number of input rows, and get the performance result:
Fix & improve.
No.
UTs.
=> [POAE7-2890] Fix core dump and improvement of HashMap

cpp/src/cider/common/Arena.h, cpp/src/cider/common/base/StringRef.cpp, cpp/src/cider/common/base/StringRef.h, cpp/src/cider/common/hashtable/HashTableKeyHolder.h
1. Add `Arena.h` based on allocators, `MemoryChunk` is the memory unit. Memory is aligned to `_SC_PAGESIZE` of operation system, and it is padded to `PADDING_FOR_SIMD` for better SIMD performance and memory efficiency.
2. Add `StringRef.h` to preserve strings. It provides high performance for strings comparison through `SSE2` instruction set, which is important for HashTable when the key type is string.
3. Add `CRC32Hash` for String, which is under `SSE4.2` instruction set.
4. Add `StringRef` and `SerializedKeyHolder` to `HashTableKeyHolder` for multiple keys support.
Add Arena and StringRef.
No.
UTs.
=> [POAE7-2864] Implementation of HashTable Arena and StringRef

cpp/src/cider/benchmarks/CMakeLists.txt, cpp/src/cider/benchmarks/HashMapBenchmark.cpp
Add std::map, std::unordered_map and folly::F14FastMap to the benchmark of HashTable.
The performance will be better if we use more efficient allocator in the future.
The conclusion is cider optimized HashTable for int8 and int16 gains
**10x-16x** performance better than folly::F14FastMap,
**15x-25x** better than cider basic HashTable,
**36x-100x** better than std::map.
The result shows below:
Improvement.
No.
UTs.
=> [POAE7-2909] Add std::map, std::unordered_map and folly::F14FastMap to HashTable benchmark

cpp/src/cider-velox/src/CiderPipelineOperator.cpp, cpp/src/cider-velox/src/CiderPlanNode.h, cpp/src/cider-velox/src/ciderTransformer/CiderPlanTransformerOptions.cpp, cpp/src/cider-velox/src/ciderTransformer/CiderPlanUtil.cpp, cpp/src/cider-velox/test/CiderOperatorTest.cpp, cpp/src/cider-velox/test/CiderOperatorTestBase.h, cpp/src/cider/exec/nextgen/context/CodegenContext.h, cpp/src/cider/exec/processor/DefaultBatchProcessor.cpp, cpp/src/cider/exec/processor/DefaultBatchProcessor.h, cpp/src/cider/exec/processor/StatefulProcessor.cpp, cpp/src/cider/exec/processor/StatefulProcessor.h, cpp/src/cider/include/cider/processor/BatchProcessor.h
compile in ciderplannode's constructor, and use the cached codegen context for every driver.
resolve duplicated compile in multi drivers
keep the old API, but use the new one internally.
benchmark
INFRA
=> [POAE7-2917]resolve duplicated compile in multi drivers

cpp/src/cider/tests/nextgen/functional/CiderMathOpNextgenTest.cpp, cpp/src/cider/type/plan/BinaryExpr.cpp
fix div by zero when `needs_error_check` is false
No
CiderMathOpNextgenTest.cpp
=> [POAE7-2910] Handle Divide by NULL in Cider

cpp/src/cider/benchmarks/CMakeLists.txt, cpp/src/cider/benchmarks/HashMapBenchmark.cpp, cpp/src/cider/benchmarks/StringHashMapBenchmark.cpp
Add benchmark of HashTable for key type string.
This benchmark generates 10k, 100k, 1M rows of data with low cardinality (~62), and run on `std::map`, `std::unordered_map`, `folly:F14FastMap` and `cider::optimized_map`.
Short string: (length = 10)
Long string: (length =500)
Improvement.
No.
UTs
=> [POAE7-2931] Add benchmark for StringHashTable

cpp/src/cider-velox/benchmark/tpch/TpchInMemBenchmark.cpp, cpp/src/cider-velox/benchmark/tpch/TpchInMemBuilder.cpp, cpp/src/cider-velox/benchmark/tpch/TpchInMemBuilder.h, cpp/src/cider/exec/operator/join/CiderJoinHashTable.cpp
Add join query based on tpc-h, `nation.n_nationkey ⋈ customer.c_nationkey`.
We can run this query by following steps:
1. Turn ENABLE_BENCHMARK on under cpp/src/cider-velox/CMakeLists.txt
2. make release
3. Cider: `/TpchInMemBenchmark -nopartial_agg_pattern -left_deep_join_pattern -run_query_verbose=23 -scale_factor=1`. 
4. Velox: `./TpchInMemBenchmark -nopartial_agg_pattern -run_query_verbose=23 -scale_factor=1`.
Improvement.
No.
UTs.
=> [POAE7-2928] Add simple join benchmark to tpch framework
