intel/BDTK

.github/workflows/main.yml

remove secret
using opensource submodule, don't need secrets anymore
No
github actions

[POAE7-2336] update actions' yaml

---

cider-velox/src/CiderOperator.cpp
cider-velox/src/ciderTransformer/CiderPlanTransformerFactory.cpp
cider-velox/src/planTransformer/PlanTransformer.cpp
cider-velox/src/planTransformer/PlanUtil.cpp
cider-velox/test/e-2-e/presto/queries/tpch/q13.sql
cider-velox/test/e-2-e/presto/queries/tpch/q15.sql
cider-velox/test/e-2-e/presto/queries/tpch/q22.sql
cider-velox/test/e-2-e/presto/queries/tpch/q4.sql
cider/exec/template/AutomaticIRMetadataGuard.h

 [POAE7-2331] fix some bugs by TPC-H

---

.github/workflows/main.yml

add timeout for build phase
avoid single thread make
No
CICD

[POAE7-2336] add timeout for CI

---

cider/tests/utils/CMakeLists.txt

Fix bug for build dependency for substrait. 
Fix build dependency for substrait, first generator substait files  when build cider.
No
Use exist UTs
bug

[POAE7-2340] Fix build dependency for substrait

---

.github/labeler.yaml

enable labels after code refactor
CICD

[POAE7-2343] Enable labels for BDTK repo

---

cider-velox/test/expression/ExprEvalUtils.cpp
cider-velox/test/expression/VeloxToCiderExpr.cpp
cider/exec/module/CiderCompileModule.cpp
cider/exec/plan/parser/ConverterHelper.cpp
cider/tests/CiderAggTestHelper.h
cider/tests/Substrait2IRTest.cpp
cider/tests/functionality/CiderFilterTest.cpp
cider/tests/functionality/CiderMathOpTest.cpp

Remove or resolve TODO and FIXME in CiderFilterTest and expression evaluation module
try to resolve TODO and FIXMEs
No
UT

[POAE7-2338] TODO and FIXME resolvement in CiderFilterTest and expression evaluation module

---

cider/exec/plan/parser/ConverterHelper.cpp
cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cider/exec/plan/parser/SubstraitToAnalyzerExpr.h
cider/exec/template/StringOpsIR.cpp
cider/function/string/StringOpInfo.cpp
cider/function/string/StringOpInfo.h
cider/function/string/StringOps.cpp
cider/function/string/StringOps.h
cider/tests/functionality/CiderStringTest.cpp
cider/tests/substrait_plan_files/functions/date/extract_year_cast_string_to_date.json
cider/tests/substrait_plan_files/functions/date/string_to_date.json
cider/tests/substrait_plan_files/functions/date/year_cast_string_to_date.json
cider/tests/utils/QueryDataGenerator.h
cider/type/data/funcannotations.h
cider/type/data/sqltypes.h
cider/type/plan/Analyzer.cpp
cider/type/plan/Analyzer.h
cider/util/Datum.cpp
cider/util/Datum.h
cider/util/sqldefs.h

1. add try-cast stringOp to support cast to date from non-encoded string
2. add date format string generating patterns for test
to support tpch for velox
No
Uts

[POAE7-2341] add try-cast stringOp to support cast to date from non-encoded string

---

cider/exec/template/GroupByAndAggregate.cpp
cider/tests/functionality/CiderGroupByTest.cpp

Enable string support in Group by and add some tests.
Improvement.
No.
UTs.
cider, test

[POAE7-2320] Support string as key/target in group by

---

cider-velox/src/RawDataConvertor.cpp
cider-velox/src/TypeConversions.h
cider-velox/test/AggWithRandomDataTest.cpp
cider-velox/test/CiderOperatorTest.cpp
cider-velox/test/planTransformerTest/CiderPlanTransformerIncludes.h
cider/tests/CiderNongroupbyAggTestHelper.h

support partial avg on col.
new feature support.
no
ut

[POAE7-1994][POAE7-2312] [41003] avg on col

---

cider/tests/functionality/CiderGroupByTest.cpp
cider/tests/utils/CiderBatchChecker.h
cider/tests/utils/CiderBatchCheckerTest.cpp

Resolve three todos in CiderBatchChecker and CiderGroupByTest.
For improvement.
No.
UTs.

[POAE7-2344] TODO and FIXME resolvement in CiderBatchChecker

---

cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cider/tests/functionality/ScalarFunctionExprTest.cpp
cider/tests/substrait_plan_files/between_and_date_velox.json

add between...and... date type support
bug fix
No
UTs
BUG

[POAE7-2366] between...and... function date type support

---

docs/develop-guide.rst

Modified /docs/develop-guide.rts to update https://intel.github.io/BDTK/develop-guide.html
mainly update how to build BDTK.
The github repo in old guidance have been discarded.  
no
no need

[POAE7-2362] update develop-guide.html

---

cider-velox/src/CiderOperator.cpp
cider-velox/src/CiderOperator.h
cider-velox/src/CiderStatefulOperator.cpp
cider/exec/module/batch/CiderBatch.cpp
cider/include/cider/batch/CiderBatch.h
cider/include/cider/batch/CiderBatchUtils.h

+ enable new data format by using gflags ```--use_cider_data_format```
+ provide test method but cannot ensure all test will past when using new data format.
+ test demands
No
local test by setting gflags

[POAE7-2346] using new data format

---

cider/tests/functionality/CiderCaseWhenTest.cpp
cider/tests/utils/CiderTestBase.cpp
cider/tests/utils/CiderTestBase.h

add sum tests for conditional queries
verify the feature
No
Uts

[POAE7-1944] add sum tests with conditional expr

---

docs/development-specification.rst
docs/index.rst

please take review @winningsix  @xieqi @Ma-Jian1 
Add exception specification documentation
Optimize exception usage
No
No
cider

[POAE7-2301]Development Specification

---

cider/exec/operator/aggregate/CiderAggHashTable.cpp
cider/exec/operator/aggregate/CiderAggTargetColExtractorTmpl.h
cider/exec/template/ArithmeticIR.cpp
cider/exec/template/CgenState.cpp
cider/exec/template/CgenState.h
cider/exec/template/ColumnIR.cpp
cider/exec/template/CompareIR.cpp
cider/exec/template/ConstantIR.cpp
cider/exec/template/DateTimeUtils.h
cider/exec/template/Execute.cpp
cider/exec/template/Execute.h
cider/exec/template/GroupByAndAggregate.cpp
cider/exec/template/GroupByAndAggregate.h
cider/exec/template/IRCodegen.cpp
cider/exec/template/LogicalIR.cpp
cider/exec/template/OutputBufferInitialization.cpp
cider/exec/template/TargetValue.h
cider/function/datetime/DateAdd.cpp
cider/function/datetime/DateTruncate.cpp
cider/function/datetime/ExtractFromTime.cpp
cider/include/cider/CiderException.h
cider/include/cider/batch/CiderBatch.h
cider/type/data/InlineNullValues.h
cider/type/plan/Analyzer.h
cider/util/Datum.cpp
cider/util/Logger.cpp
cider/util/Logger.h
cider/util/SqlTypesLayout.h
cider/util/TypedDataAccessors.h

please take review @winningsix @xieqi  @Ma-Jian1 
replace abort with CiderUnsupportedException
Code Refactor
No
UT
cider

[POAE7-2369]replace abort

---

cider/exec/template/LogicalIR.cpp

Workaround for Nullability Problem Under NOT IS NULL Expression.
Plan from Velox will always notes nullability as nullable. However, IS NULL expression should be not nullable, which will lead to codegen problem under old data format.
No.
UTs.
Bug
Pls take a review @Ma-Jian1

[POAE7-2368][Hot Fix] Workaround for Nullability Problem Under NOT IS NULL Expression.

---

cider-velox/test/e-2-e/presto/queries/tpch/q7.sql
cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cider/tests/functionality/CiderStringTest.cpp
cider/tests/substrait_plan_files/cast_str_to_date_implictly.json

between...and... str support
cast str to date workaround to fix tpch q7.
No
UTs
BUG

[POAE7-2366] between...and... string support(cast str to date tpch-q7 workaround)

---

cider-velox/test/e-2-e/presto/queries/tpch/q2.sql
cider/exec/module/CiderRuntimeModule.cpp
cider/include/cider/CiderRuntimeModule.h

Fix incorrect string conversion due to slot offset
incorrect offset for extract column
No
Using exist UTs
cider

[POAE7-2370] Incorrect string conversion

---

cider/exec/module/CiderTypes.cpp
cider/exec/plan/parser/ConverterHelper.cpp
cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cider/exec/plan/parser/SubstraitToAnalyzerExpr.h
cider/include/cider/CiderTypes.h
cider/include/cider/batch/CiderBatch.h
cider/tests/functionality/CiderMathOpTest.cpp
cider/tests/functionality/DateTypeQueryTest.cpp
cider/tests/substrait_plan_files/add_timestamp_interval_day.json
cider/tests/substrait_plan_files/add_timestamp_interval_month.json
cider/tests/substrait_plan_files/add_timestamp_interval_second.json
cider/tests/substrait_plan_files/cast_date_as_timestamp.json
cider/tests/substrait_plan_files/cast_literal_timestamp.json
cider/tests/substrait_plan_files/cast_timestamp_as_date.json
cider/tests/substrait_plan_files/extract/microsecond_of_timestamp.json
cider/tests/substrait_plan_files/extract/second_of_time.json
cider/tests/utils/CiderBatchBuilder.h
cider/tests/utils/CiderBatchBuilderTest.cpp
cider/tests/utils/CiderBatchChecker.cpp
cider/tests/utils/CiderQueryRunner.cpp
cider/tests/utils/DuckDbQueryRunner.cpp
cider/tests/utils/DuckDbQueryRunnerTest.cpp
cider/tests/utils/QueryDataGenerator.h
cider/tests/utils/QueryDataGeneratorTest.cpp
cider/type/data/sqltypes.h

refactor cider time type and add time func
cider feature support
No
UTs
CODEREFACTOR

[POAE7-2351] refactor cider time type and add time func

---

cider-velox/test/e-2-e/presto/queries/tpch/q1.sql
cider-velox/test/e-2-e/presto/queries/tpch/q10.sql
cider-velox/test/e-2-e/presto/queries/tpch/q11.sql
cider-velox/test/e-2-e/presto/queries/tpch/q12.sql
cider-velox/test/e-2-e/presto/queries/tpch/q14.sql
cider-velox/test/e-2-e/presto/queries/tpch/q16.sql
cider-velox/test/e-2-e/presto/queries/tpch/q17.sql
cider-velox/test/e-2-e/presto/queries/tpch/q18.sql
cider-velox/test/e-2-e/presto/queries/tpch/q19.sql
cider-velox/test/e-2-e/presto/queries/tpch/q20.sql
cider-velox/test/e-2-e/presto/queries/tpch/q3.sql
cider-velox/test/e-2-e/presto/queries/tpch/q5.sql
cider-velox/test/e-2-e/presto/queries/tpch/q8.sql
cider-velox/test/e-2-e/presto/queries/tpch/q9.sql

[POAE7-2383] turn on all passed TPC-H queries

---

cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cider/exec/plan/parser/Translator.cpp
cider/exec/template/CgenState.h
cider/exec/template/Execute.cpp
cider/exec/template/ExpressionRewrite.cpp
cider/exec/template/InValuesIR.cpp
cider/tests/functionality/CiderFilterTest.cpp
cider/tests/functionality/CiderStringTest.cpp
cider/tests/substrait_plan_files/in_string_2_array_with_substr.json
cider/tests/substrait_plan_files/in_string_array.json
cider/tests/substrait_plan_files/in_string_array_with_substr.json
cider/tests/utils/CiderTestBase.cpp

in varchar array support
support in varchar semantics for tpc-h
No
UT

[POAE7-2352] IN(varchar) support

---

cider/exec/plan/parser/Translator.cpp
cider/tests/functionality/CiderGroupByTest.cpp

Fix bug of unsupport tinyint and smallint simple qual filter and agg is not null filter.
Fix bug of unsupport tinyint and smallint simple qual filter and agg is not null filter.
No
UTs
BUG,cider,test

[POAE7-2263] Unsupport tinyint and smallint simple qual filter

---

cider/exec/operator/aggregate/CiderAggHashTable.cpp
cider/exec/operator/aggregate/CiderAggHashTable.h
cider/exec/template/TargetExprBuilder.cpp

- Remove keyless and columnar-layout related code in CiderAggHashTable.
- Fix offset bug under group-by w/o aggregations.
- Fix mistake introduced by previous conflict resolve.
Bug fix.
No
UTs
BugFix
Pls take a review @harborn @winningsix

[POAE7-2380] [HotFix] Groupby HashTable Code Refactor and Bugfix

---

cider-velox/src/RawDataConvertor.cpp
cider-velox/test/DataConvertorTest.cpp

+ old data converter support constant encoding
+ lack of this feature
No
UTs

[POAE7-2386] data converter support constant encoding

---

cider/include/cider/CiderTypes.h
cider/tests/functionality/DateTypeQueryTest.cpp
cider/tests/substrait_plan_files/add_timestamp_interval_mixed.json

Some improvement and add test cases.
Improvement.
No.
UTs.

[POAE7-2157] [Cider test development] TIMESTAMP/INTERVAL DAY TO SECOND/INTERVAL YEAR TO MONTH

---

cider-velox/src/CiderVeloxPluginCtx.cpp
cider-velox/src/CiderVeloxPluginCtx.h
cider-velox/src/ciderTransformer/CiderPlanPatterns.h
cider-velox/src/planTransformer/PatternRewriter.h
cider-velox/src/planTransformer/PlanBranches.cpp
cider-velox/src/planTransformer/PlanNodeAddr.cpp
cider-velox/src/planTransformer/PlanNodeAddr.h
cider-velox/src/planTransformer/PlanTransformer.cpp
cider-velox/src/planTransformer/PlanTransformer.h
cider-velox/src/planTransformer/PlanUtil.cpp
cider-velox/src/planTransformer/SequencePlanPattern.h
cider-velox/test/e-2-e/presto/queries/tpch/q16.sql

[POAE7-2391] Fix bug of PlanPattern write race under multi-threading

---

cider/tests/functionality/CiderCaseWhenTest.cpp
cider/tests/functionality/CiderStringTest.cpp

add more test for coalesce syntax, reorg existing TCs
test feature
No
UT

[POAE7-2260] add more test for coalesce

---

ci/docker/scripts-cider/cider-deps-ubuntu.sh
cider/exec/template/operator/join/hashtable/BaselineJoinHashTable.cpp
cider/exec/template/operator/join/hashtable/OverlapsJoinHashTable.cpp
cider/exec/template/operator/join/hashtable/RangeJoinHashTable.cpp
cider/exec/template/operator/join/hashtable/builders/BaselineHashTableBuilder.h
cider/exec/template/operator/join/hashtable/builders/PerfectHashTableBuilder.h
cider/tests/functionality/CiderHashJoinTest.cpp
cider/tests/utils/CiderTestBase.cpp

1.  change join hash table building to single thread from cpu_threads
2.  updates hash join tests
1. As a library, cider should not use all the threads.
2.  Previous join tests had problems so updates
No
Uts

[POAE7-2388] change join hash table building to single thread and update previous tests

---

cider/exec/module/CiderRuntimeModule.cpp
cider/exec/module/batch/CiderBatch.cpp
cider/exec/module/batch/CiderBatchUtils.cpp
cider/exec/operator/aggregate/CiderAggTargetColExtractorBuilder.cpp
cider/exec/template/CountDistinct.h
cider/exec/template/NativeCodegen.cpp
cider/include/cider/batch/CiderBatch.h
cider/include/cider/batch/CiderBatchUtils.h
cider/include/cider/batch/ScalarBatch.h
cider/include/cider/batch/StructBatch.h
cider/tests/CiderAggHashTableTest.cpp
cider/tests/CiderAggTestHelper.h
cider/tests/CiderArrowBatchTest.cpp
cider/tests/CiderNongroupbyAggTestHelper.h
cider/tests/functionality/CiderFilterTest.cpp
cider/tests/utils/CiderBatchChecker.cpp
cider/tests/utils/CiderBatchChecker.h
cider/tests/utils/CiderQueryRunner.cpp
cider/tests/utils/CiderQueryRunner.h
cider/tests/utils/CiderTestBase.cpp
cider/tests/utils/CiderTestBase.h

1. reuse current cider batch data generator, and convert to arrow based batch in test. will not convert null data currently.
2. for result check, just compare row/column num with duck result, didn't verify actual data.
3. will replace with new utils.

[POAE7-2333] Arrow based batch test framework

---

cider-velox/src/RawDataConvertor.cpp
cider-velox/src/TypeConversions.h
cider-velox/test/e-2-e/presto/queries/tpch/q16.sql
cider-velox/test/e-2-e/presto/queries/tpch/q21.sql
cider/type/schema/CiderSchemaProvider.cpp

[POAE7-2443] call loadedVector if DictionaryVector is a lazy vector

---

CMakeLists.txt
ci/docker/Dockerfile.centos-8
ci/docker/Dockerfile.ubuntu-20.04
ci/docker/build-image.sh
ci/docker/install.sh
ci/docker/llvm-9-glibc-2.31-708430-remove-cyclades.patch
cider/exec/operator/aggregate/CiderAggSpillBufferMgr.cpp

Add centos support
Add centos build
No
Use exist UT
CICD

[POAE7-2393] Add centos build support

---

cider/exec/plan/parser/PlanRelVisitor.cpp
cider/exec/plan/parser/PlanRelVisitor.h
cider/exec/plan/parser/RelVisitor.cpp
cider/exec/plan/parser/RelVisitor.h
cider/exec/plan/parser/SubstraitToRelAlgExecutionUnit.cpp
cider/exec/plan/parser/VariableContext.cpp
cider/exec/plan/parser/VariableContext.h

fix bug in col name
bug
No
UTs
BUG

[POAE7-2435] fix col name

---

cider/exec/module/batch/CiderBatchUtils.cpp
cider/exec/template/CodeGenerator.h
cider/exec/template/DateTimeIR.cpp
cider/exec/template/IRCodegen.cpp
cider/exec/template/operator/aggregate/CiderAggregateCodeGenerator.cpp
cider/tests/CMakeLists.txt
cider/tests/CiderAggTestHelper.h
cider/tests/CiderDateFunctionTest.cpp
cider/tests/functionality/DateTypeQueryTest.cpp

+ add date(include timestamp) related functions
+ date_add
+ date_diff
+ date_trunc
+ use workaround UTs to test
+ use simple self-constructed EUs to test
+ use flag ''--log-severity=DEBUG4 to print detailed result
+ lack of these functions when using new data format
No
UTs and log

[POAE7-2406] support date function

---

cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cider/exec/plan/parser/SubstraitToAnalyzerExpr.h
cider/exec/template/DateTimeTranslator.cpp
cider/exec/template/DateTimeTranslator.h
cider/function/datetime/ExtractFromTime.h
cider/tests/functionality/DateTypeQueryTest.cpp
cider/tests/substrait_plan_files/functions/date/day.json
cider/tests/substrait_plan_files/functions/date/day_of_week.json
cider/tests/substrait_plan_files/functions/date/day_of_year.json
cider/tests/substrait_plan_files/functions/date/month.json
cider/tests/substrait_plan_files/functions/date/quarter.json
cider/tests/substrait_plan_files/functions/date/week.json

directly support presto date extract functions like month(), day(), day_of_year()....
support upstream Uts
No
UTs
CODEREFACTOR

[POAE7-2453]directly support presto date extract functions 

---

cider-velox/src/CiderPlanNodeTranslator.h

[POAE7-2464] turn on multi-threading drivers

---

ci/scripts/integrate-presto-cider.sh
ci/scripts/setup-adapters.sh
docs/user/quick-start.rst

Added initial user guide and added script to install hdfs adaptor. 
NO
Able to install and integration following the guide 
Integration and documentation.

[POAE7-2433] Added HDFS adapter scripts and initialized user guide. 

---

cider/tests/utils/ArrowArrayBuilder.h
cider/tests/utils/ArrowArrayBuilderTest.cpp
cider/tests/utils/QueryArrowDataGenerator.h
cider/tests/utils/QueryArrowDataGeneratorTest.cpp

Support BOOL for arrow format, add related function in ArrowArrayBuilder and QueryArrowArrayGenerator
add Unit Test in corresponding test files

[POAE7-2465]Support BOOL for arrow format

---

.github/workflows/update-gh-pages.yml

+ Now detects all changes under ```docs``` directory instead of just ```.rst``` file.
+ docs structure changed
No
git actions

[POAE7-2468] update gh-pages build rule

---

ci/scripts/build-presto-package.sh
ci/scripts/integrate-presto-cider.sh
ci/scripts/setup-libhdfs.sh
docs/user/quick-start.rst

Preparation for BDTK release 0.9.0
No
Review on the guide. 
documentation & veloxIntegration

[POAE7-2486] Modified user guide and integration scripts for release 0.9.0

---

cider/exec/template/Codec.cpp
cider/exec/template/Codec.h
cider/exec/template/ColumnIR.cpp
cider/exec/template/operator/aggregate/CiderAggregateCodeGenerator.cpp
cider/function/aggregate/CiderRuntimeFunctions.h
cider/include/cider/batch/ScalarBatch.h
cider/tests/CiderAggHashTableTest.cpp
cider/tests/CiderAggTestHelper.h
cider/tests/CiderArrowBatchTest.cpp

Change bool input and output format from 8-bit to 1-bit as arrow format in Codegen component. 
Migrate to arrow format.
No
UTs
Infra
Pls take a review @jikunshang @winningsix

[POAE7-2482] Modify BOOL Related Codegen to Support bit-packed BOOL in Arrow Format.

---

cider/exec/template/ArithmeticIR.cpp
cider/exec/template/CodeGenerator.h
cider/exec/template/CompareIR.cpp
cider/exec/template/IRCodegen.cpp
cider/exec/template/InValuesBitmap.cpp
cider/exec/template/InValuesBitmap.h
cider/exec/template/InValuesIR.cpp
cider/function/scalar/RuntimeFunctions.cpp
cider/tests/functionality/CiderFilterTest.cpp

Switch InValues codegen to Arrow format
Arrow migration
No
UT

[POAE7-2416] In Ops using Arrow Format

---

cider-velox/src/ciderTransformer/CiderPlanPatterns.cpp
cider-velox/src/ciderTransformer/CiderPlanPatterns.h
cider-velox/src/ciderTransformer/CiderPlanTransformerFactory.cpp
cider-velox/src/planTransformer/PatternRewriter.h
cider-velox/test/CiderOperatorTest.cpp

add partialAgg Pattern
make more computation  offloading to cider 
No
UT

[POAE7-2363]PartialAggPattern support

---

cider/exec/module/batch/CiderBatchUtils.cpp
cider/include/cider/batch/CiderBatchUtils.h
cider/tests/utils/ArrowArrayBuilder.h
cider/tests/utils/ArrowArrayBuilderTest.cpp
cider/tests/utils/QueryArrowDataGenerator.h
cider/tests/utils/QueryArrowDataGeneratorTest.cpp

1. Support utf8 string for arrow format, able to generate string column randomly.
2. add toString function for arrow format.
3. resolve some comments.
NO
add Unit Tests

[POAE7-2466]support VARCHAR data generation for arrow format

---

cider-velox/src/RawDataConvertor.cpp
cider-velox/test/DataConvertorTest.cpp

+ correct Date Type converter (velox to cider、cider to velox)
+ add related test
+ add Date Type converter with dictionary encoding and related test
+ add Date Type converter with constant encoding and related test
+ support e2e test
No
UTs and log

[POAE7-2458] support date convert and test(old data format)

---

CMakeLists.txt
README.md
cider/exec/module/CMakeLists.txt
cider/function/CMakeLists.txt

BDTK release v0.9
RC for v0.9
No
Use exist UTs
cider

[POAE7-2461] Preparing BDTK release v0.9

---

cider/function/CMakeLists.txt

Fix select the correct gcc-toolchain for LLVM
No
Use exist UTs
cider

[POAE7-2488] Fix for select the correct gcc toolchain

---

ci/docker/scripts-cider/cider-deps-ubuntu.sh

add a step for firstly building thrift followed by thrift's github repo
Resolve error for firstly building docker image of BDTK 
No
Local test

[POAE7-2513][BUG]add step for first build thrift

---

cider-velox/src/CiderPlanNode.h
cider-velox/src/CiderPlanNodeTranslator.h
cider-velox/src/RawDataConvertor.cpp
cider-velox/src/TypeConversions.h
cider-velox/src/ciderTransformer/CiderPlanPatterns.cpp
cider-velox/src/ciderTransformer/CiderPlanPatterns.h
cider-velox/src/ciderTransformer/CiderPlanRewriter.cpp
cider-velox/src/ciderTransformer/CiderPlanRewriter.h
cider-velox/src/ciderTransformer/CiderPlanUtil.cpp
cider-velox/src/ciderTransformer/CiderPlanUtil.h
cider-velox/src/planTransformer/PatternRewriter.h
cider-velox/src/planTransformer/PlanBranches.cpp
cider-velox/src/planTransformer/PlanBranches.h
cider-velox/src/planTransformer/PlanNodeAddr.cpp
cider-velox/src/planTransformer/PlanNodeAddr.h
cider-velox/src/planTransformer/PlanPattern.cpp
cider-velox/src/planTransformer/PlanPattern.h
cider-velox/src/planTransformer/PlanRewriter.cpp
cider-velox/src/planTransformer/PlanRewriter.h
cider-velox/src/planTransformer/PlanTransformer.cpp
cider-velox/src/planTransformer/PlanTransformer.h
cider-velox/src/planTransformer/PlanUtil.cpp
cider-velox/src/planTransformer/PlanUtil.h
cider-velox/src/planTransformer/SequencePlanPattern.cpp
cider-velox/src/planTransformer/SequencePlanPattern.h

Code refactor to passing references with const qualifier instead of passing value  for memory consideration
improve code quality
No
Passed existing UT
veloxIntegration

[POAE7-2525] [Code Refactor] [Cider-Velox] Code refactor to passing references with const qualifier instead of passing value  for memory consideration

---

cider/exec/module/batch/CiderBatch.cpp
cider/include/cider/batch/CiderBatch.h
cider/tests/CiderArrowBatchTest.cpp
cider/tests/functionality/PrimitiveTypeArrowTest.cpp
cider/tests/functionality/PrimitiveTypeQueryArrowTest.cpp
cider/tests/utils/ArrowArrayBuilder.h
cider/tests/utils/ArrowArrayBuilderTest.cpp
cider/tests/utils/QueryArrowDataGenerator.h

1. add PrimitiveTypeArrowTest & PrimitiveTypeQueryArrowTest
2. Move ArrowArrayBuilder::toString to CiderBatch::toStringForArrow
3. fix divided by 0 and memory leak bugs
No
Unit Test

[POAE7-2428]verify Primitive Type for Arrow Format

---

cider/exec/module/batch/CiderBatchUtils.cpp

Fix Non Groupby Agg Arrow Format null value.
Fix Non Groupby Agg Arrow Format null value.
No.
Uts.
BUG,cider,test

[POAE7-2526] Fix Non Groupby Agg Arrow Format null value.

---

cider/exec/template/CompareIR.cpp
cider/function/aggregate/CiderRuntimeFunctions.h
cider/tests/functionality/CiderFilterTest.cpp

add distinct from support and update filter Op tests for Arrow
No
UT

[POAE7-2423] add distinct from support and update filter Op tests for Arrow

---

cider/exec/operator/aggregate/CiderAggHashTable.cpp
cider/exec/operator/aggregate/CiderAggHashTable.h
cider/exec/operator/aggregate/CiderAggTargetColExtractorTmpl.h
cider/exec/template/CastIR.cpp
cider/exec/template/CodeGenerator.h
cider/exec/template/CompareIR.cpp
cider/exec/template/Execute.cpp
cider/exec/template/Execute.h
cider/exec/template/IRCodegen.cpp
cider/exec/template/StringOpsIR.cpp
cider/exec/template/TargetExprBuilder.cpp
cider/function/aggregate/CiderRuntimeFunctions.h
cider/function/aggregate/GroupByRuntime.cpp
cider/tests/CiderAggHashTableTest.cpp
cider/tests/functionality/CiderStringTest.cpp
cider/type/plan/Analyzer.cpp

add string op (like substring) support for arrow format.
1. refactor string hasher
2. like function support.
3. add string op codegen support, add some uts
4. string test leverage new dataGenerator/batchChecker
NO
UT.

[POAE7-2490] String op support for arrow format

---

cider/exec/nextgen/jitlib/JITLib.h
cider/exec/nextgen/jitlib/base/JITFunction.h
cider/exec/nextgen/jitlib/base/JITTuple.h
cider/exec/nextgen/jitlib/base/JITValue.h
cider/exec/nextgen/jitlib/base/ValueTypes.h
cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.cpp
cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.h
cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.h
cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp
cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.h
cider/tests/nextgen/jitlib/JITLibTest.cpp

+ support JITTuple
+ related test
+ support nextgen
No
UTs
INFRA

[POAE7-2522] Support JITTuple

---

cider/exec/nextgen/OpNode.h
cider/exec/nextgen/OpPipeline.h
cider/exec/nextgen/Parser.h
cider/exec/nextgen/Transformer.h
cider/exec/nextgen/Translator.h
cider/tests/nextgen/CMakeLists.txt
cider/tests/nextgen/compiler/CMakeLists.txt
cider/tests/nextgen/compiler/NextgenCompilerTest.cpp

initial commit for next-gen compiler framework API
API for next-gen compiler
No
Add a UT
cider

[POAE7-2516] Next-gen compiler framework API

---

Makefile
cider/exec/template/CodeGenerator.h
cider/exec/template/ColumnIR.cpp
cider/exec/template/IRCodegen.cpp
cider/tests/functionality/CiderHashJoinTest.cpp
cider/tests/utils/QueryArrowDataGenerator.h

1. support left-join for arrow format
2. update left-join filter push down codegen
support arrow format migration
No
Uts

[POAE7-2527] Support Left-join for Arrow format

---

cider/exec/nextgen/CMakeLists.txt
cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.cpp
cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.h

Add the IR optimization function before build(), provide the optimize options.
If necessary, optimization options will be adjusted later.
Support the Next Gen framework
No
UTs
INFRA

[POAE7-2532] IR Optimization Options Support

---

ci/scripts/build-presto-package.sh

Hotfix and enabled HDFS in packaging script. 
NO
Nightly building. 
CICD

[POAE7-2514] Fixed bugs and support HDFS in packaging

---

cider/exec/nextgen/jitlib/base/JITFunction.h
cider/exec/nextgen/jitlib/base/JITValue.h
cider/exec/nextgen/jitlib/base/JITValueOperations.h
cider/exec/nextgen/jitlib/llvmjit/LLVMJITControlFlow.cpp
cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.cpp
cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.h
cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.cpp
cider/exec/nextgen/jitlib/llvmjit/LLVMJITUtils.h
cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp
cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.h
cider/tests/nextgen/jitlib/JITLibTest.cpp

Support JITPointer related operations.
For nextgen query compiler.
No
UTs
Infra
Pls take a review @Ma-Jian1 @xieqi @winningsix @jikunshang

[POAE7-2521] JITPointer Operations Support.

---

cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cider/exec/template/CastIR.cpp
cider/exec/template/CodeGenerator.h
cider/exec/template/ColumnIR.cpp
cider/function/scalar/RuntimeFunctions.cpp
cider/tests/functionality/CiderCastTest.cpp
cider/tests/functionality/CiderFilterTest.cpp

codegen cast func code refactor with arrow format.
code refactor with arrow format migration.
No
UTs
CODEREFACTOR

[POAE7-2512] cast func numeric type support with arrow format

---

cider/tests/functionality/CiderGroupByTest.cpp

Add arrow test for GroupBy.
Improve.
No.
UTs.

[POAE7-2427]  Verify Groupby Expr for Arrow Format

---

cider/exec/module/CiderRuntimeModule.cpp
cider/exec/module/batch/CiderBatchUtils.cpp
cider/tests/functionality/CiderAggArrowTest.cpp

1. verify **non-groupby** Agg Ops for ArrowFormat except paritialAVG and countDistinct.
2. fix COUNT result is NULL when use arrow as input. 
NO
CiderAggArrowTest.cpp

[POAE7-2426] verify Agg Ops for Arrow Format

---

ci/scripts/build-presto-package.sh

Added libgsasl.so* and libntlm.so* to packaged lib directory. 
No
Daily CICD with packaging. 
CICD

[POAE7-2514][Hot fix] Added libs to packaging scripts. 

---

cider/exec/template/StringOpsIR.cpp

[ Hotfix ] Correct bit width calculation for logical size considering old and new data format

---

README.md

Update README to highlight project motivation.
To have more explainable project intro.
No.
Local verified.
documentation

[ Minor Fix ] Update README doc to highlight project motivations

---

cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cider/tests/functionality/CiderStringTest.cpp
cider/tests/substrait_plan_files/substr.json
cider/util/sqldefs.h

Latest velox dependency removed function mapping (from presto name to substrait name), which will not convert `substr` to `substring`, lead to some queries failed. Just add this work around for hot fix. Need to redesign to resolve such issues.
No.
UT

[POAE7-2593][hot fix] Fix substr issue due to velox version upgrade.

---

cider/exec/operator/aggregate/CiderAggTargetColExtractorBuilder.cpp
cider/exec/operator/aggregate/CiderAggTargetColExtractorTmpl.h
cider/tests/functionality/CiderGroupByTest.cpp

Add agg extractor for group by bool and enable related test cases.
Arrow format support.
No.
UTs.

[POAE7-2575] Support Groupby Bool for Arrow Format

---

ci/scripts/build-presto-package.sh

add presto depend
In order for Prestodb.tar.gz to be able to run in ubuntu container
No
UT
CICD

[POAE7-2585]add presto depend

---

cider-velox/src/CiderOperator.cpp
cider-velox/src/CiderStatelessOperator.cpp

+  supply data format convert method in stateless operator
+ fix some logical error 
+ new data format usage
+ No
+ UTs - use flag ```--use_cider_data_format```
INFRA

[POAE7-2584] Enable Arrow data format in output convertor leveraging Velox Arrow bridge

---

cider/exec/nextgen/jitlib/base/JITFunction.h
cider/exec/nextgen/jitlib/base/JITModule.h
cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.h
cider/tests/nextgen/jitlib/JITLibTest.cpp
cider/tests/nextgen/translator/FilterProjectTest.cpp

+ add a builder to created function conveniently
+ JITFunction can only be created by JITFunctionBuilder
+ change related test usage
+ old function creation method have a certain cost of use
+ finish member method is easy to forget
No.
UTs
INFRA

[POAE7-2579] JITFunction builder

---

ci/scripts/build-presto-package.sh
ci/scripts/presto-bdtk-9dbb0f9.patch
docs/user/quick-start.rst

Change the presto repository to prestodb
Deprecated intel-bigdata/presto
No
UT
CICD

[POAE7-2595]Change the presto repository to prestodb

---

cider/tests/functionality/CiderConstantQueryTest.cpp
cider/tests/functionality/CiderFilterTest.cpp
cider/tests/functionality/CiderGroupByTest.cpp
cider/tests/functionality/CiderStringTest.cpp
cider/tests/functionality/SimpleCiderTest.cpp
cider/tests/utils/CiderTestBase.cpp
cider/tests/utils/CiderTestBase.h

migrate test cases to arrow format
No
UT

[POAE7-2580]Arrow format test migration

---

ci/scripts/build-presto-package.sh

please take review @xieqi @Ma-Jian1 
modify patch path
The path of patch is wrong
No
CICD
CICD

[POAE7-2595]modify patch path

---

cider/exec/template/ColumnIR.cpp
cider/exec/template/IRCodegen.cpp
cider/tests/functionality/CiderNonEqualLoopJoinTest.cpp
cider/tests/utils/CiderTestBase.cpp
cider/tests/utils/CiderTestBase.h

1. support loop join for arrow format
2. updated loop join codegen for left join type
3. commented out columnvar fetch
support arrow format
No
Uts

[POAE7-2582] support loop join for arrow format

---

cider/exec/operator/aggregate/CiderAggHashTable.cpp
cider/exec/operator/aggregate/CiderAggHashTable.h
cider/exec/operator/aggregate/CiderAggTargetColExtractorTmpl.h
cider/exec/template/common/descriptors/QueryMemoryDescriptor.cpp
cider/exec/template/common/descriptors/QueryMemoryDescriptor.h
cider/tests/functionality/CiderAggArrowTest.cpp

1. verify COUNT GROUP BY for arrow format & fix bug for groupby agg when COUNT result is 0
2. add TCs that all the inputs are NULL for CiderAggArrowTest 
No
CiderAggArrowTest.cpp

[POAE7-2590] verify COUNT with groupby for arrow format

---

cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cider/exec/template/CgenState.h
cider/exec/template/ConstantIR.cpp
cider/exec/template/StringOpsIR.cpp
cider/tests/CompileWorkUnitTest.cpp
cider/tests/functionality/CiderStringTest.cpp
cider/tests/utils/QueryArrowDataGenerator.h
cider/util/DateTimeParser.cpp
cider/util/DateTimeParser.h
cider/util/Datum.cpp

add cast string to numeric type in stringOps handle.
New format support
No
UTs

[POAE7-2543] cast string to numeric type with arrow format in stringOps

---

cider/exec/template/CgenState.h

fix date constant value overflow
bug fixed, not detected in previous CI.
No
UTs

[Hotfix] fix date constant value overflow caused by format migration

---

cider/tests/functionality/CiderHashJoinTest.cpp

add more tests about hash join for arrow array format
test coverage
No
Uts

[POAE7-2581] migrate complex join tests to arrow format

---

cider-velox/test/e-2-e/presto/queries/scalar_function.sql

please take review @Ma-Jian1 @xieqi @kyotoyx 
Replace customer_bucketed with customer in scalar_function.sql
The customer_bucketed data table does not exist
No
E to E
CICD

[POAE7-2607]Replace customer_bucketed with customer

---

ci/scripts/build-presto-package.sh

please take review @xieqi @Ma-Jian1 @kyotoyx 
add extensions/*.ymal
The package file needs to contain extensions/*.ymal files
No
CICD
CICD

[POAE-2609]add extensions/*.ymal

---

cider/exec/nextgen/operators/FilterNode.cpp
cider/exec/nextgen/operators/FilterNode.h
cider/exec/nextgen/operators/OpNode.h
cider/exec/nextgen/operators/ProjectNode.cpp
cider/exec/nextgen/operators/ProjectNode.h
cider/exec/nextgen/operators/SourceNode.cpp
cider/exec/nextgen/operators/SourceNode.h
cider/exec/nextgen/parsers/RelAlgEUParser.cpp
cider/exec/nextgen/transformer/CMakeLists.txt
cider/exec/nextgen/transformer/Transformer.cpp
cider/exec/nextgen/transformer/Transformer.h
cider/exec/plan/parser/GeneratorContext.h
cider/tests/nextgen/compiler/NextgenCompilerTest.cpp
cider/tests/nextgen/compiler/ParserTest.cpp

Support basic Transformer FW
For nextgen proj.
No
UTs
Infra
Pls take a review @Ma-Jian1 @xieqi @winningsix

[POAE7-2583] Basic Transformer framework support.

---

cider-velox/test/e-2-e/presto/queries/scalar_function.sql

please take review @winningsix @kyotoyx @xieqi @Ma-Jian1 
Modify the customer data table ds column name in sql to address column name
The ds column does not exist in the customer data table
NO
CICD
CICD

[POAE7-2607] modify table customer col ds to address

---

cider/exec/template/CastIR.cpp
cider/exec/template/CodeGenerator.h
cider/exec/template/InValuesIR.cpp
cider/exec/template/StringOpsIR.cpp
cider/function/aggregate/CiderRuntimeFunctions.h
cider/tests/functionality/CiderCastTest.cpp
cider/util/misc.cpp
cider/util/misc.h

support cast primitive type into string
feature support.
No
UTs

[POAE7-2594] cast numeric type into string type support

---

cider-velox/benchmark/CMakeLists.txt
cider-velox/src/RawDataConvertor.cpp
cider-velox/test/CMakeLists.txt
cider-velox/test/CiderOperatorHashJoinTest.cpp
cider-velox/test/DataConvertorTest.cpp
cider-velox/test/RangedBatchGenerator.h
cider-velox/test/SubstraitTest/VeloxPlanFragmentSubstraitConverterTest.cpp
cider/exec/plan/parser/ConverterHelper.cpp

[POAE7-2485] update codes for velox branch ww43

---

cider-velox/src/CiderJoinBuild.cpp
cider-velox/src/CiderJoinBuild.h
cider-velox/src/CiderOperator.cpp
cider-velox/src/CiderOperator.h
cider-velox/test/CiderOperatorHashJoinTest.cpp
cider-velox/test/CiderOperatorTestBase.h

Pass UTs with project node after enable join pattern
No
existing UT after enable join pattern manually
veloxIntegration, test

[POAE7-2479] Use share_ptr<CiderBatch> for join bridge

---

cider/exec/nextgen/Context.h
cider/exec/nextgen/context/Batch.h
cider/exec/nextgen/context/CodegenContext.cpp
cider/exec/nextgen/context/CodegenContext.h
cider/exec/nextgen/context/ContextRuntimeFunctions.h
cider/exec/nextgen/operators/ArrowSourceNode.cpp
cider/exec/nextgen/operators/CMakeLists.txt
cider/exec/nextgen/operators/ColumnToRowNode.cpp
cider/exec/nextgen/operators/RowToColumnNode.cpp
cider/exec/nextgen/operators/RowToColumnNode.h
cider/tests/nextgen/operator/RowToColumnTest.cpp

- add RowToColumnNode and RowToColumnTranslator op
- add related test, modify MockRowToColumnSink with RowToColumnTranslator, pass the filter-project workflow
For Next Gen Framework support
No
UTs
INFRA

[POAE7-2621] RowToColumnTranslator support

---

cider/exec/plan/validator/CiderPlanValidator.cpp
cider/exec/plan/validator/CiderPlanValidator.h
cider/exec/plan/validator/SingleNodeValidator.cpp
cider/exec/plan/validator/SingleNodeValidator.h
cider/tests/CMakeLists.txt
cider/tests/plan/CiderPlanValidatorTest.cpp
cider/tests/substrait_plan_files/cider_pv_invalid_agg.json
cider/tests/substrait_plan_files/cider_pv_invalid_join.json
cider/tests/substrait_plan_files/cider_pv_invalid_read.json
cider/tests/substrait_plan_files/cider_pv_multi_join.json

wrap planslice as substrait plan and do RelAlgEU generation
No
UT

[POAE7-2591] wrap planslice as substrait plan and do RelAlgEU generation

---

ci/scripts/build-presto-package.sh
ci/scripts/presto-bdtk-67b3bf.patch

please take review @xieqi @Ma-Jian1 @winningsix 
build-presto-package.sh and patch file
velox switch to WW43
No
CICD
CICD

[POAE7-2633]build-presto-package switch to WW43

---

cider/exec/module/CiderRuntimeModule.cpp
cider/exec/operator/aggregate/CiderAggTargetColExtractorTmpl.h
cider/tests/functionality/CiderAggArrowTest.cpp
cider/tests/substrait_plan_files/multi_fp_groupby_avg_partial.json
cider/tests/utils/CiderQueryRunner.cpp

add Test Case that ParitialAVG with groupby for arrow format
No
CiderAggArrowTest.cpp

[POAE7-2599] verify PartialAVG with groupby for arrow format

---

cider/exec/module/CiderRuntimeModule.cpp
cider/exec/module/batch/CiderBatchUtils.cpp
cider/include/cider/batch/CiderBatchUtils.h
cider/tests/functionality/CiderAggArrowTest.cpp
cider/tests/utils/ArrowArrayBuilder.h
cider/tests/utils/ArrowArrayBuilderTest.cpp

support STRUCT result for non-groupby agg for arrow format
No
CiderAggArrowTest

[POAE7-2627] support STRUCT result for non-groupby agg for arrow format

---

cider/exec/nextgen/context/Batch.cpp
cider/exec/nextgen/utils/FunctorUtils.h

Add Y-combinator based recursive function warpper to replace some ```std::function``` usage.
Code improvement.
No
UTs
Infra

[POAE7-2636] Template base Lambda wapper to replace some std::function

---

cider/exec/nextgen/jitlib/base/JITValue.h
cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp
cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.h
cider/exec/nextgen/operators/ColumnToRowNode.cpp
cider/exec/nextgen/operators/RowToColumnNode.cpp
cider/tests/nextgen/functional/CMakeLists.txt
cider/tests/nextgen/functional/CiderCastNextgenTest.cpp
cider/type/plan/UnaryExpr.cpp
cider/type/plan/UnaryExpr.h

support primitive type cast func in nextgen
nextgen compiler
No
new UTs

[POAE7-2625] support primitive type cast func in nextgen

---

cider/exec/module/CiderRuntimeModule.cpp
cider/exec/module/batch/CiderBatch.cpp
cider/include/cider/batch/CiderBatch.h
cider/tests/functionality/CiderAggArrowTest.cpp

support STRUCT result for groupby agg for arrow format.
Specifically handle groupby Partial AVG in fetch result stage.
No
CiderAggArrowTest.cpp

[POAE7-2647] support STRUCT result for groupby agg for arrow format

---

cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp
cider/tests/nextgen/functional/CiderExprNextgenTest.cpp
cider/tests/nextgen/functional/jsons/is_distinct_from.json
cider/tests/nextgen/functional/jsons/is_not_distinct_from.json
cider/type/plan/BinaryExpr.cpp
cider/type/plan/BinaryExpr.h

support IS DISTINCT FROM codegen
support IS DISTINCT FROM codegen
No
UT

[POAE7-2624] support is distinct from for nextgen

---

cider/exec/nextgen/context/CodegenContext.cpp
cider/exec/nextgen/jitlib/base/JITFunction.h
cider/exec/nextgen/jitlib/base/JITValue.h
cider/exec/nextgen/jitlib/base/JITValueOperations.h
cider/exec/nextgen/jitlib/base/ValueTypes.h
cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.cpp
cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.h
cider/exec/nextgen/operators/ColumnToRowNode.cpp
cider/exec/nextgen/operators/FilterNode.cpp
cider/exec/nextgen/operators/RowToColumnNode.cpp
cider/tests/nextgen/jitlib/JITLibTest.cpp

- Add createLiteral for literal constant creation.
- Refactor createLocalJITValue to support recursive calling.
- Remove std::function from createLocalJITValue.
- Improve createVariable for setting initial value.
For nextgen
No
UTs
Infra

[POAE7-2634] JITLib Code Improvement & Refactor

---

cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp
cider/tests/nextgen/jitlib/JITLibTest.cpp

modify JITValue Logical operations return type
bug-fix
No
UTs
FIX

[POAE7-2670] [Hot-fix]modify JITValue Logical operations return type

---

cider/exec/nextgen/operators/ColumnToRowNode.cpp
cider/exec/nextgen/operators/RowToColumnNode.cpp
cider/exec/nextgen/utils/TypeUtils.h
cider/tests/nextgen/functional/CiderExprNextgenTest.cpp
cider/type/plan/BinaryExpr.cpp
cider/type/plan/BinaryExpr.h

Add logical op &&/|| and bool type support
expr codegen for nextgen
No
UT

[POAE7-2659] logical op and bool type support

---

cider/exec/nextgen/context/Buffer.h
cider/exec/nextgen/context/CodegenContext.cpp
cider/exec/nextgen/context/CodegenContext.h
cider/exec/nextgen/context/ContextRuntimeFunctions.h
cider/exec/nextgen/context/RuntimeContext.cpp
cider/exec/nextgen/context/RuntimeContext.h
cider/tests/nextgen/compiler/CMakeLists.txt
cider/tests/nextgen/compiler/ContextTest.cpp

+ add buffer related function in codegen context
+ buffer registration used by agg and etc.
No.
UTs
INFRA

[POAE7-2664] add context buffer

---

cider/tests/nextgen/compiler/FilterProjectTest.cpp
cider/type/plan/ConstantExpr.cpp

fix constant codegen for tiny/small/bigint
bugfix
No
UT
INFRA

[POAE7-2673] fix constant codegen for smallint/bigint etc.

---

cider-velox/src/substrait/VeloxPlanFragmentToSubstraitPlan.cpp
cider-velox/test/SubstraitTest/VeloxPlanFragmentSubstraitConverterTest.cpp
cider-velox/test/e-2-e/presto/queries/orderby_limit_topn.sql

- Update velox submodule
- Support OrderBy/TopN/Limit Node in cider-velox part.
new feature support.
No.
UT.

[POAE7-2672] Support order by/ top-n/ limit node in cider-velox

---

cider/exec/nextgen/operators/ArrowSourceNode.cpp

Fix input column index in ArrowSourceOp.
ArrowSourceOp generated wrong index when loading child input ArrowArray.
No
UTs
BugFix
Pls take a review @kd97 @jikunshang

[POAE7-2699] [HotFix] Fix input column index in ArrowSourceOp.

---

cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.cpp

Refine LLVMJIT IR dump result.
For nextgen.
No
No need.
Infra

[POAE7-2680] LLVMJIT IR Dump Result Refinement

---

cider/exec/nextgen/context/CodegenContext.cpp
cider/exec/nextgen/context/ContextRuntimeFunctions.h
cider/exec/nextgen/operators/ColumnToRowNode.cpp
cider/exec/nextgen/operators/RowToColumnNode.cpp
cider/exec/nextgen/utils/JITExprValue.h
cider/function/scalar/RuntimeFunctions.cpp
cider/tests/nextgen/compiler/FilterProjectTest.cpp

support string type C2R, R2C, could run query like select col_string from table.
No
UT.

[POAE7-2686]string type C2R, R2C support

---

cider-velox/test/CiderOperatorTest.cpp
cider/tests/CiderNongroupbyAggTest.cpp
cider/tests/CiderNongroupbyAggTestHelper.h

1. verify PartialAVG for cider-velox for arrow format
2. remove final avg UT for arrow format
No
cider/tests/CiderNongroupbyAggTest.cpp
cider-velox/test/AggWithRandomDataTest.cpp

[POAE7-2683] verify PartialAVG for cider-velox for arrow format

---

cider-velox/src/BitUtils.h
cider-velox/src/CiderVeloxPluginCtx.cpp
cider-velox/src/CiderVeloxPluginCtx.h
cider/function/FunctionLookupEngine.cpp
cider/function/FunctionLookupEngine.h

[POAE7-2693] make FunctionLookupEngine yaml file path configurable

---

README.md
docs/user.rst
docs/user/modules.rst
docs/user/modules/ICL-module.rst
docs/user/modules/expr-eval-module.rst
docs/user/modules/hash-table-module
docs/user/modules/operators-module

update document for BDTK provided module description
for document.
No.
UT
documentation

[POAE7-2710] Add functional module description

---

src/cider/exec/nextgen/context/Buffer.h
src/cider/exec/nextgen/context/CodegenContext.cpp
src/cider/exec/nextgen/context/CodegenContext.h
src/cider/exec/nextgen/context/RuntimeContext.cpp
src/cider/exec/nextgen/jitlib/base/ValueTypes.h
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.cpp
src/cider/exec/nextgen/operators/AggregationNode.cpp
src/cider/exec/nextgen/operators/AggregationNode.h
src/cider/exec/nextgen/operators/CMakeLists.txt
src/cider/exec/nextgen/operators/OperatorRuntimeFunctions.h
src/cider/exec/nextgen/parsers/RelAlgEUParser.cpp
src/cider/function/CMakeLists.txt
src/cider/function/scalar/RuntimeFunctions.cpp
src/cider/tests/nextgen/compiler/AggTest.cpp
src/cider/tests/nextgen/compiler/CMakeLists.txt
src/cider/type/plan/Analyzer.h

+ support simple agg translator (sum)
+ add related logic in paser
+ add related runtime function
+ add related test
+ add initializer in context buffer
+ agg translator implement
No
UTs
INFRA

[POAE7-2689] simple non-groupby agg translator (support sum)

---

src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.h
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.h

Use ```TargetMachine``` for more precise compile configuration control.
Performance evaluation.
No
Unnecessary
Infra
Pls take a review @Ma-Jian1 @winningsix

[POAE7-2682] LLVMJIT TargetMachine Configuration

---

ci/scripts/build-presto-package.sh
ci/scripts/presto-bdtk-67b3bf.patch

please take review @xieqi @Ma-Jian1 
modify ci/scripts/build-presto-package.sh and ci/scripts/presto-bdtk-67b3bf.patch
support config yaml patch
No
CICD
CICD

[POAE-2633]update presto patch

---

src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.h
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.h

Add LLVMJIT ASM Dump feature.
Performance evaluation.
No
Unnecessary
Infra
~~Pending on #251~~
Pls take a review @Ma-Jian1 @xieqi @winningsix

[POAE7-2681] LLVMJIT ASM Dump

---

src/cider/exec/nextgen/context/RuntimeContext.h
src/cider/exec/nextgen/context/StringHeap.h
src/cider/include/cider/CiderAllocator.h
src/cider/tests/CMakeLists.txt
src/cider/tests/StringHeapTest.cpp

Add string util(ArenaAllocator, StringHeap) for next gen compiler.
for string op workflow
NO
UT

[POAE7-2714] Add String util for next gen compiler

---

src/cider/tests/nextgen/functional/PrimitiveTypeQueryNextgenTest.cpp

Migrate PrimitiveQuery tests to nextgen
PrimitiveTypeBooleanQueryTest
PrimitiveTypeFloatQueryTest
PrimitiveTypeDoubleQueryTest
PrimitiveTypeTinyintQueryTest
PrimitiveTypeSmallintQueryTest
PrimitiveTypeIntegerQueryTest
PrimitiveTypeBigintQueryTest
PrimitiveTypeFloatMinQueryTest
PrimitiveTypeFloatMaxQueryTest
PrimitiveTypeDoubleMinQueryTest
PrimitiveTypeDoubleMaxQueryTest
PrimitiveTypeTinyintMinQueryTest
PrimitiveTypeTinyintMaxQueryTest
PrimitiveTypeSmallintMinQueryTest
PrimitiveTypeSmallintMaxQueryTest
PrimitiveTypeIntegerMinQueryTest
PrimitiveTypeIntegerMaxQueryTest
PrimitiveTypeBigintMinQueryTest
PrimitiveTypeBigintMaxQueryTest
PrimitiveTypeMixQueryTest
NO
tests/nextgen/functional/PrimitiveTypeQueryNextgenTest.cpp

[POAE7-2712] Migrate PrimitiveQuery tests to nextgen

---

src/cider-velox/src/CiderHashJoinBuild.cpp
src/cider-velox/src/CiderHashJoinBuild.h
src/cider-velox/src/CiderPipelineOperator.cpp
src/cider-velox/src/CiderPipelineOperator.h
src/cider/exec/module/CiderRuntimeModule.cpp
src/cider/exec/nextgen/context/CodegenContext.h
src/cider/exec/processor/DefaultBatchProcessor.cpp
src/cider/exec/processor/DefaultBatchProcessor.h
src/cider/exec/processor/DefaultJoinHashTableBuilder.cpp
src/cider/exec/processor/DefaultJoinHashTableBuilder.h
src/cider/exec/processor/JoinHandler.cpp
src/cider/exec/processor/JoinHandler.h
src/cider/exec/processor/StatefulProcessor.cpp
src/cider/exec/processor/StatefulProcessor.h
src/cider/exec/processor/StatelessProcessor.cpp
src/cider/exec/processor/StatelessProcessor.h
src/cider/include/cider/processor/BatchProcessor.h
src/cider/include/cider/processor/BatchProcessorContext.h
src/cider/include/cider/processor/JoinHashTableBuilder.h
src/cider/tests/CMakeLists.txt
src/cider/tests/processor/CMakeLists.txt
src/cider/tests/processor/CiderBatchProcessorTest.cpp

Add nextgen compile support for stateless processor
Support nextgen compile for stateless processor
No
Add new batchProcessor test case
cider

[POAE7-2668] Add nextgen compile support for StatelessProcessor

---

src/cider-velox/test/expression/CMakeLists.txt
src/cider-velox/test/expression/VeloxToCiderExpr.cpp
src/cider/function/FunctionLookupEngine.cpp
src/cider/function/FunctionLookupEngine.h
src/cider/function/internals/functions_arithmetic.yaml
src/cider/function/internals/functions_string.yaml
src/cider/tests/functionality/FunctionLookUpTest.cpp

Updata in function yaml-file and code to support in:str_list
Update velox test case code to support function mapping between presto and cider.
Updata in function yaml-file to support in:str_list
No
Uts
cider

[POAE7-2702] Updata in function yaml-file to support in:str_list

---

src/cider/tests/functionality/FunctionLookUpTest.cpp

Hotfix for FunctionLookupTest build failure
hotfix
No
CI/CD

[POAE7-2736] Hotfix for FunctionLookupTest build failure

---

src/cider/CMakeLists.txt
src/cider/benchmarks/CMakeLists.txt
src/cider/benchmarks/JITlibBenchmark.cpp
src/cider/exec/nextgen/jitlib/base/ValueTypes.h
src/cider/tests/nextgen/CMakeLists.txt
src/cider/tests/nextgen/benchmark/CMakeLists.txt
src/cider/tests/nextgen/benchmark/JITlibBenchmark.cpp
src/cider/type/data/funcannotations.h
src/cider/util/CMakeLists.txt

Basic Benchmark for JITlib
Performance evaluation
No
unnecessary
INFRA

[POAE7-2711] JITLib Basic Performance Benchmark versus g++

---

src/cider/exec/nextgen/function/CiderStringFunctions.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.cpp
src/cider/tests/nextgen/jitlib/JITLibTest.cpp

Fix Wrong Function Declaration Copy Procedure in cloneFunctionRecursive()
BugFix
BugFix
Pls take a review @kd97 @yma11

[POAE7-2749] [Hotfix] Fix Wrong Function Declaration Copy Procedure in cloneFunctionRecursive()

---

src/cider/exec/nextgen/context/RuntimeContext.cpp
src/cider/exec/nextgen/operators/AggregationNode.cpp
src/cider/exec/nextgen/operators/OperatorRuntimeFunctions.h
src/cider/exec/nextgen/operators/extractor/AggExtractor.h
src/cider/tests/nextgen/compiler/AggTest.cpp

+ agg function support null
+ optimize codegen branch
+ refactor test
+ null support
No
UTs
INFRA

[POAE7-2717] agg_support_null_optimization

---

ci/docker/Dockerfile
ci/docker/Dockerfile.centos-8
ci/docker/Dockerfile.ubuntu-20.04
ci/docker/install.sh
ci/docker/scripts-presto/velox/scripts/setup-ubuntu.sh

please take review @xieqi @Ma-Jian1 
update protobuf to 3.21.4 and install nasm
update protobuf to 3.21.4 and install nasm
No
CICD
CICD

[POAE7-2743]update protobuf to 3.21.4 and install nasm

---

src/cider/exec/module/batch/ArrowABI.h
src/cider/exec/processor/DefaultBatchProcessor.cpp
src/cider/tests/nextgen/compiler/NextgenCompilerTest.cpp
src/cider/tests/utils/CMakeLists.txt
src/cider/tests/utils/CiderArrowChecker.cpp
src/cider/tests/utils/CiderArrowChecker.h
src/cider/tests/utils/CiderArrowCheckerTest.cpp
src/cider/tests/utils/CiderNextgenQueryRunner.cpp
src/cider/tests/utils/CiderNextgenQueryRunner.h
src/cider/tests/utils/CiderNextgenQueryRunnerTest.cpp
src/cider/tests/utils/CiderNextgenTestBase.cpp
src/cider/tests/utils/CiderNextgenTestBase.h
src/cider/tests/utils/DuckDbQueryRunner.cpp
src/cider/tests/utils/DuckDbQueryRunner.h

Use BatchProcessor API for CiderQueryRunner
Use BatchProcessor API for CiderQueryRunner
No
Use exist UTs
cider

[POAE7-2706] Use BatchProcessor API for CiderQueryRunner

---

.github/workflows/main.yml
ci/scripts/presto-integration.sh

please take review @xieqi @kyotoyx 
Optimize CICD process
Optimize CICD process
No
CICD
CICD

[POAE7-2753]Optimize CICD process

---

CMakeLists.txt
Makefile
ci/scripts/lint_inclusions.txt
cmake-modules/FindArrow.cmake
cmake-modules/FindArrowTesting.cmake
src/compression/CMakeLists.txt
src/compression/benchmark/BenchmarkMain.cpp
src/compression/benchmark/CMakeLists.txt
src/compression/benchmark/CompressionBenchmark.cpp
src/compression/codec/igzip_codec.cpp

Add benchmark for ICL
Add benchmark for ICL
No
use benchmark
infa

[POAE7-2722] Add benchmark for ICL

---

src/cider/exec/nextgen/jitlib/CMakeLists.txt
src/cider/exec/nextgen/jitlib/base/JITModule.h
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.h
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.h
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITTargets.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITTargets.h

Add Target Information to LLVMJITModule
For IR Optimization
No
Unnecessary
INFRA

[POAE7-2745] Add Target Information to LLVMJITModule

---

Makefile
src/cider-velox/src/Allocator.h
src/cider-velox/test/SubstraitTest/SubstraitAggregationTest.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.cpp
src/cider/exec/operator/aggregate/CiderAggSpillBufferMgr.cpp
src/cider/exec/template/Execute.cpp
src/cider/tests/CiderCompileModuleTest.cpp
src/cider/tests/CiderRuntimeModuleJoinTest.cpp
src/cider/tests/Sql2IR.cpp
src/cider/tests/Substrait2IRTest.cpp
src/cider/tests/nextgen/functional/CiderExprNextgenTest.cpp
src/cider/tests/plan/CiderPlanValidatorTest.cpp
src/cider/tests/utils/CiderNextgenQueryRunner.cpp
src/cider/tests/utils/DuckDbArrowAdaptor.h
src/cider/type/data/string/StringDictionary.cpp
src/cider/util/Logger.cpp
src/cider/util/Logger.h
src/cider/util/Regexp.cpp
src/cider/util/StringTransform.cpp
src/cider/util/StringTransform.h
src/cider/util/filesystem/cider_path.cpp
src/cider/util/memory/DataMgr.cpp
src/cider/util/memory/DataMgr.h
src/cider/util/toString.h

Reverts intel/BDTK#289 since this PR make ci failed

Revert "[POAE7-2756] replace boost codes by using stl"

---

ci/scripts/lint_exclusions.txt
ci/scripts/lint_inclusions.txt
src/cider/common/hashtable/FixedHashMap.h
src/cider/common/hashtable/FixedHashTable.h
src/cider/common/hashtable/Hash.h
src/cider/common/hashtable/HashMap.h
src/cider/common/hashtable/HashTable.h

Enable cpplint of cider/common.
Improvement.
No.
CI

[POAE7-2752] Enable cpplint of cider/common

---

src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.h
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.h

Upgrade Optimization PassManager from Legacy PM to New PM
JITLib Optimization
No
UTs
Infra

[POAE7-2746] Upgrade Optimization PassManager from Legacy PM to New PM

---

src/cider/benchmarks/JITlibBenchmark.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.h
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.cpp
src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITModule.h

JITLib Auto-Vectorize Support: SSE
Add auto-vectorization support.
No
UTs
INFRA

[POAE7-2731] JITLib Auto-Vectorize Support: SSE

---

src/cider/tests/nextgen/functional/PrimitiveTypeNextgenTest.cpp

Migrate PrimitiveType tests to Nextgen
No
tests/nextgen/functional/PrimitiveTypeNextgenTest.cpp

[POAE7-2754] Migrate PrimitiveType tests to Nextgen

---

src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITControlFlow.cpp

Fix memory leak in LLVMIfBuilder
BugFix
No
UTs
BugFix

[POAE7-2767] Fix memory leak in LLVMIfBuilder

---

ci/scripts/presto-bdtk-67b3bf.patch

please take review @xieqi @Ma-Jian1 
modify presto-bdtk-67b3bf.patch
add cider_processor cider_plan_substrait
No
CICD
CICD

[POAE7-2633]add cider_processor cider_plan_substrait

---

src/cider/exec/nextgen/context/CiderSet.h
src/cider/exec/nextgen/function/CiderSetFunctions.cpp
src/cider/tests/nextgen/functional/StringTest.cpp
src/cider/type/plan/InValues.cpp
src/cider/type/plan/InValues.h

IN expr support for string type in Nextgen
IN expr support for string type in Nextgen
No
UT

[POAE7-2750] IN expr support for string type in Nextgen

---

src/cider/exec/nextgen/context/CiderSet.h
src/cider/tests/nextgen/functional/FilterTest.cpp
src/cider/type/plan/BinaryExpr.cpp
src/cider/type/plan/BinaryExpr.h

What changes were proposed in this pull request?
support string Distinct From in nextgen
Why are the changes needed?
support string Distinct From in nextgen
Does this PR introduce any user-facing change?
No
How was this patch tested?
UT
Which label does this PR belong to?

[POAE7-2766] Support distinct from for String

---

cmake-modules/BuildUtils.cmake
cmake-modules/FindParquet.cmake
src/compression/benchmark/CMakeLists.txt
src/compression/benchmark/CompressionBenchmark.cpp
src/compression/benchmark/ParquetBenchmark.cpp
src/compression/codec/CMakeLists.txt
src/compression/common/igzip/CMakeLists.txt

Add parquet reader benchmark for ICL use igzip
use arrow native gzip codec
<pre>
-------------------------------------------------------------------------
Benchmark               Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------
BM_ParquetRead 4007742029 ns   4007095682 ns            1 bytes_per_second=40.4892M/s ratio=1.84323
</pre>
use ICL igzip codec
<pre>
-------------------------------------------------------------------------
Benchmark               Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------
BM_ParquetRead 3034097632 ns   3034034889 ns            1 bytes_per_second=51.4797M/s ratio=1.91298
</pre>
Add parquet reader benchmark
No …

[POAE7-2761] Add parquet reader benchmark for ICL

---

ci/scripts/intel_copyright_files.txt
src/cider/examples/CMakeLists.txt
src/cider/examples/CiderHashTableExample.cpp
src/cider/exec/operator/join/BaseHashTable.h
src/cider/exec/operator/join/CiderLinearProbingHashTable.cpp
src/cider/exec/operator/join/CiderLinearProbingHashTable.h
src/cider/exec/operator/join/CiderStdUnorderedHashTable.h
src/cider/exec/operator/join/HashTableFactory.cpp
src/cider/exec/operator/join/HashTableFactory.h
src/cider/tests/hashtable/CiderHashTableTest.cpp
src/cider/tests/nextgen/compiler/ContextTest.cpp

add hashtable builder factory , base interface and example
base interface as hashtbale's impl's common api
build factory will be used in hashtable selector in future
add an example to illustrate how hashtable is used
No
Uts

[POAE7-2726] add hashtable builder factory , base interface and example

---

src/cider/exec/nextgen/context/CodegenContext.cpp
src/cider/exec/nextgen/context/CodegenContext.h
src/cider/exec/nextgen/operators/AggregationNode.cpp
src/cider/exec/nextgen/operators/AggregationNode.h
src/cider/exec/nextgen/operators/OperatorRuntimeFunctions.h
src/cider/exec/nextgen/operators/extractor/AggExtractorBuilder.cpp
src/cider/exec/nextgen/operators/extractor/AggExtractorBuilder.h
src/cider/tests/nextgen/compiler/AggTest.cpp

+ add count agg function (support int8/16/32/64)
+ lack of count function
No
UTs
INFRA

[POAE7-2691] non groupby agg support count

---

src/cider/tests/nextgen/functional/SimpleCiderNextgenTest.cpp

Migrate SimpleCiderTest tot nextgen
SimpleCiderTestBase.selectTest
SimpleCiderTestBase.nullTest
No
tests/nextgen/functional/SimpleCiderNextgenTest.cpp

[POAE7-2792] Migrate SimpleCiderTest to nextgen

---

src/cider/tests/nextgen/functional/CiderMathOpNextgenTest.cpp
src/cider/type/plan/BinaryExpr.cpp
src/cider/type/plan/BinaryExpr.h

fix error check(mathop) in null value
bug fixed
No
UTs

[POAE7-2768] fix error check in null value

---

src/cider/exec/nextgen/context/CodegenContext.cpp
src/cider/exec/nextgen/context/CodegenContext.h
src/cider/exec/nextgen/operators/AggregationNode.cpp
src/cider/exec/nextgen/operators/OperatorRuntimeFunctions.h
src/cider/exec/nextgen/operators/extractor/AggExtractorBuilder.cpp
src/cider/exec/plan/parser/TypeUtils.h
src/cider/tests/nextgen/compiler/AggTest.cpp

+ support min/max agg function in next gen module
+ support int8/16/32/64 type
+ fix bug in sqltypeinfo convertor
+ add new extractors
+ optimize AggExprsInfo
+ support agg function
No
UTs
INFRA

[POAE7-2780] Agg support min max

---

docs/user/quick-start.rst
src/cider-velox/src/ciderTransformer/CiderPlanPatterns.cpp
src/cider-velox/src/ciderTransformer/CiderPlanPatterns.h
src/cider-velox/src/ciderTransformer/CiderPlanTransformerFactory.cpp
src/cider-velox/src/ciderTransformer/CiderPlanTransformerOptions.cpp
src/cider-velox/src/ciderTransformer/CiderPlanTransformerOptions.h
src/cider-velox/src/planTransformer/PatternRewriter.h
src/cider-velox/test/CiderOperatorTestBase.h
src/cider-velox/test/CiderPatternTest.cpp

add project pattern in ciderPlanTransformer
To run e2e tests and make there will have a single pattern to support project node to make it split up with agg node.
No.
UT

[POAE7-2806] Add ProjectPattern for ciderPlanTransformer

---

src/cider/exec/plan/substrait/SubstraitPlan.cpp
src/cider/exec/plan/substrait/SubstraitPlan.h
src/cider/exec/processor/DefaultBatchProcessor.cpp
src/cider/exec/processor/DefaultBatchProcessor.h
src/cider/exec/processor/StatefulProcessor.cpp
src/cider/exec/processor/StatefulProcessor.h
src/cider/exec/processor/StatelessProcessor.cpp
src/cider/tests/nextgen/compiler/NextgenCompilerTest.cpp
src/cider/tests/processor/CiderBatchProcessorTest.cpp
src/cider/tests/utils/CiderArrowChecker.cpp
src/cider/tests/utils/CiderNextgenQueryRunner.cpp

Add non-groupby support for stateful processor
Add non-groupby support for stateful processor
No
Add new UTs to test
cider

[POAE7-2794] BatchProcessor API for stateful pipeline

---

cpp/src/cider-velox/src/ciderTransformer/CiderPlanPatterns.cpp
cpp/src/cider-velox/src/ciderTransformer/CiderPlanPatterns.h
cpp/src/cider-velox/src/ciderTransformer/CiderPlanTransformerFactory.cpp
cpp/src/cider-velox/src/ciderTransformer/CiderPlanTransformerOptions.cpp
cpp/src/cider-velox/src/ciderTransformer/CiderPlanTransformerOptions.h
cpp/src/cider-velox/src/planTransformer/PatternRewriter.h
cpp/src/cider-velox/test/CiderOperatorTestBase.h
cpp/src/cider-velox/test/CiderPatternTest.cpp
docs/user/quick-start.rst

Revert "[POAE7-2806] Add ProjectPattern for ciderPlanTransformer"

---

cpp/src/cider/exec/nextgen/operators/AggregationNode.cpp
cpp/src/cider/tests/nextgen/functional/AggFunctionTest.cpp
cpp/src/cider/tests/utils/CiderArrowChecker.cpp

+ migrate agg test
+ skip unsupported test
+ test process next batch and nextgen
No
UTs
INFRA

[POAE7-2816] migrate agg test

---

cpp/src/cider/benchmarks/JITlibBenchmark.cpp
cpp/src/cider/exec/nextgen/jitlib/base/JITControlFlow.h
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITControlFlow.cpp
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITControlFlow.h
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.cpp
cpp/src/cider/exec/nextgen/operators/HashJoinNode.cpp
cpp/src/cider/tests/nextgen/jitlib/JITLibTest.cpp

Support continue semantic for LoopBuilder.
Support Left Join
No
UTs
INFRA

[POAE7-2811] Support continue in LoopBuilder.

---

cpp/src/cider/tests/nextgen/functional/CaseWhenTest.cpp
cpp/src/cider/type/plan/CaseExpr.cpp

[POAE7-2618] case/coalesce/if expr support in next codegen.
This story will be divided into four subtasks:
[POAE7-2675] primitive type if-then expr support in next codegen.
[POAE7-2781] primitive type multiple case-when expr support in next codegen.
[POAE7-2782] string type if/case expr support in next codegen.
[POAE7-2783] coalesce expr support in next codegen.
Implement [POAE7-2782] in this pr.
string type if/case expr support in next codegen
No.
UTs.
cider

[POAE7-2782] string type if/case expr support in next codegen

---

cpp/src/cider/exec/nextgen/context/CodegenContext.h
cpp/src/cider/exec/nextgen/context/RuntimeContext.cpp
cpp/src/cider/exec/nextgen/context/RuntimeContext.h
cpp/src/cider/exec/nextgen/operators/AggregationNode.cpp
cpp/src/cider/exec/nextgen/operators/CMakeLists.txt
cpp/src/cider/exec/nextgen/operators/QueryFuncInitializer.cpp
cpp/src/cider/exec/nextgen/operators/QueryFuncInitializer.h
cpp/src/cider/exec/nextgen/operators/RowToColumnNode.cpp
cpp/src/cider/exec/nextgen/parsers/RelAlgEUParser.cpp
cpp/src/cider/exec/nextgen/utils/JITExprValue.h
cpp/src/cider/type/plan/ColumnExpr.cpp
cpp/src/cider/type/plan/ColumnExpr.h
cpp/src/cider/type/plan/Expr.h

Move output batch registration to the beginning of query_func.
To support vectorize translators, moving output batch registration to the beginning will reduce copy and move between intermediate array and output array. 
No
UTs
INFRA

[POAE7-2813] ArrowSourceNode Refactor to Register Output Batch

---

cpp/src/cider-velox/src/CiderPipelineOperator.cpp

assign input to CiderPipelineOperator
bug fix
No
UT
veloxIntegration

Fix bug of CiderPipelineOperator

---

cpp/src/cider/exec/plan/parser/TypeUtils.h
cpp/src/cider/tests/utils/ArrowArrayBuilder.h
cpp/src/cider/tests/utils/ArrowArrayBuilderTest.cpp
cpp/src/cider/tests/utils/QueryArrowDataGenerator.h
cpp/src/cider/tests/utils/QueryArrowDataGeneratorTest.cpp

Support single dimension array in ArrowArrayBuilder&QueryDataGenerator
No
ArrowArrayBuilderTest.cpp
QueryArrowDataGeneratorTest.cpp

[POAE7-2807] Support Array in ArrowArrayBuilder&QueryDataGenarator

---

cpp/src/cider/tests/nextgen/functional/CaseWhenTest.cpp
cpp/src/cider/type/plan/CaseExpr.cpp

use  CiderNextgenTestBase to upgrade if/case-when/coalesce test case
use  CiderNextgenTestBase to upgrade if/case-when/coalesce test case
No.
Uts.
cider

[POAE7-2827] use  CiderNextgenTestBase to upgrade if/case-when/coalesce test case

---

cpp/src/cider/exec/nextgen/function/CiderStringFunctions.cpp
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.h
cpp/src/cider/tests/nextgen/functional/StringTest.cpp
cpp/src/cider/tests/utils/CiderNextgenTestBase.cpp
cpp/src/cider/type/plan/Analyzer.cpp
cpp/src/cider/type/plan/Analyzer.h
cpp/src/cider/type/plan/StringOpExpr.cpp
cpp/src/cider/type/plan/StringOpExpr.h

add string function support(regexp_extract, regexp_substr). enable skipped uts.
No
UTs.

[POAE7-2822] add string function support(regexp_extract, regexp_substr)

---

cpp/src/cider/common/interpreters/AggregationHashTable.cpp
cpp/src/cider/common/interpreters/AggregationHashTable.h
cpp/src/cider/tests/CiderNewAggHashTableTest.cpp
cpp/src/cider/tests/CiderNewHashTableTest.cpp

1. Add float and double type support for `AggregationHashTable`.
2. Add related test cases.
Implementation.
No.
UTs.

[POAE7-2774] HashTable implementation of float and double

---

cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp
cpp/src/cider/tests/nextgen/functional/CastTest.cpp
cpp/src/cider/tests/substrait_plan_files/cast_bool_to_integer.json
cpp/src/cider/tests/substrait_plan_files/cast_bool_to_tinyint.json
cpp/src/cider/type/plan/UnaryExpr.cpp

- support cast bool type. In some cases it will be converted to case...when... expr, use generated json file to test direct bool conversion.
- clean up code
pass presto e-2-e sql tests. @PenghuiJiao  pls take a review.
No
UTs

[POAE7-2848] Fix bugs in cast bool expr

---

cpp/src/cider/exec/module/batch/CiderArrowBufferHolder.cpp
cpp/src/cider/exec/module/batch/CiderArrowBufferHolder.h
cpp/src/cider/exec/nextgen/Nextgen.cpp
cpp/src/cider/exec/nextgen/context/CodegenContext.cpp
cpp/src/cider/exec/nextgen/context/CodegenContext.h
cpp/src/cider/exec/nextgen/operators/AggregationNode.h
cpp/src/cider/exec/nextgen/operators/CMakeLists.txt
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.cpp
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.h
cpp/src/cider/exec/nextgen/operators/OpNode.h
cpp/src/cider/exec/nextgen/operators/RowToColumnNode.cpp
cpp/src/cider/exec/nextgen/operators/RowToColumnNode.h
cpp/src/cider/exec/nextgen/operators/VectorizedProjectNode.cpp
cpp/src/cider/exec/nextgen/operators/VectorizedProjectNode.h
cpp/src/cider/exec/nextgen/transformer/Transformer.cpp
cpp/src/cider/exec/nextgen/transformer/Transformer.h
cpp/src/cider/exec/nextgen/utils/ExprUtils.h
cpp/src/cider/exec/nextgen/utils/JITExprValue.h
cpp/src/cider/exec/nextgen/utils/TypeUtils.h
cpp/src/cider/function/scalar/RuntimeFunctions.cpp
cpp/src/cider/tests/nextgen/compiler/NextgenCompilerTest.cpp
cpp/src/cider/type/plan/Analyzer.h
cpp/src/cider/type/plan/BinaryExpr.cpp
cpp/src/cider/type/plan/BinaryExpr.h
cpp/src/cider/type/plan/ColumnExpr.cpp
cpp/src/cider/type/plan/ColumnExpr.h
cpp/src/cider/type/plan/Expr.h
cpp/src/cider/type/plan/LikeExpr.h
cpp/src/cider/util/CiderBitUtils.h

Vectorize Project Op Support
Improve performance through SIMD
No
Basic UT.
INFRA
Pls take a review @winningsix @Ma-Jian1

[POAE7-2795] Vectorize Project Op Support

---

cpp/src/cider/tests/nextgen/functional/ConstantQueryTest.cpp

Migrate ConstantQueryTest to NextgenTestBase. 
No
UT.

[POAE7-2858] Migrate ConstantQueryTest

---

ci/scripts/build-presto-package.sh
ci/scripts/presto-bdtk-67b3bf.patch
ci/scripts/presto-integration.sh

please take review @xieqi @kyotoyx 
1. update integration script
2. update build presto package script
BDTK source file directory structure adjustment
No
UT
CICD

[POAE7-2855]update integration script

---

cpp/src/cider/exec/nextgen/context/RuntimeContext.cpp
cpp/src/cider/exec/nextgen/operators/AggregationNode.cpp
cpp/src/cider/exec/nextgen/operators/OperatorRuntimeFunctions.h
cpp/src/cider/exec/nextgen/operators/extractor/AggExtractor.h
cpp/src/cider/tests/nextgen/compiler/AggTest.cpp
cpp/src/cider/tests/nextgen/functional/AggFunctionTest.cpp

+ agg function support data type : float/double
+ test past except which contains sum(float), because because count(float) in duckdb output type is double, is not same with cider
+ complete data type
No
UTs
INFRA

[POAE7-2847] agg func support float/double

---

cpp/src/cider/exec/module/batch/CiderArrowBufferHolder.h
cpp/src/cider/exec/module/batch/CiderBatchUtils.cpp
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITUtils.h
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.cpp
cpp/src/cider/exec/nextgen/operators/RowToColumnNode.cpp
cpp/src/cider/exec/nextgen/utils/JITExprValue.h
cpp/src/cider/exec/nextgen/utils/TypeUtils.h
cpp/src/cider/include/cider/batch/CiderBatchUtils.h
cpp/src/cider/tests/nextgen/compiler/CMakeLists.txt
cpp/src/cider/tests/nextgen/compiler/DecimalOpTest.cpp
cpp/src/cider/tests/utils/ArrowArrayBuilder.h
cpp/src/cider/type/plan/BinaryExpr.cpp
cpp/src/cider/util/SqlTypesLayout.h

- Decimal Arrow type => Decimal JITValue type
- Rescale algorithm in decimal codegen expr
- decimal binop(Arithmetic/Compare) support
decimal binop support(sql functionality test will cover in next PR)
No
UTs

[POAE7-2838] decimal binary expr support in nextgen

---

cpp/src/cider/exec/nextgen/context/RuntimeContext.h
cpp/src/cider/exec/processor/DefaultBatchProcessor.cpp

destroy stringheap after processNextBatch call to reduce memory consumption.
reduce memory consumption for string functions.
No
ut

[POAE7-2857]destroy stringheap after processNextBatch call 

---

cpp/src/cider/exec/module/batch/CiderBatchUtils.cpp
cpp/src/cider/exec/nextgen/context/RuntimeContext.h
cpp/src/cider/exec/nextgen/function/CiderStringFunctions.cpp
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.cpp
cpp/src/cider/exec/nextgen/operators/QueryFuncInitializer.cpp
cpp/src/cider/exec/nextgen/operators/RowToColumnNode.cpp
cpp/src/cider/exec/nextgen/utils/JITExprValue.h
cpp/src/cider/exec/nextgen/utils/TypeUtils.h
cpp/src/cider/exec/plan/parser/ConverterHelper.cpp
cpp/src/cider/exec/plan/parser/TypeUtils.h
cpp/src/cider/tests/nextgen/compiler/ArrayTest.cpp
cpp/src/cider/tests/nextgen/compiler/CMakeLists.txt

1. Support **ARRAY** data type in ColumnReader&ColumnWriter.
2. Simply test **ARRAY**.
No
tests/nextgen/compiler/ArrayTest

[POAE7-2808] Support Array in ColumnToRowNode&RowToColumnNode

---

cpp/src/cider/exec/nextgen/context/Buffer.h
cpp/src/cider/exec/nextgen/context/CodegenContext.h
cpp/src/cider/exec/nextgen/context/RuntimeContext.cpp
cpp/src/cider/exec/nextgen/jitlib/base/JITFunction.h
cpp/src/cider/exec/nextgen/operators/HashJoinNode.cpp
cpp/src/cider/exec/nextgen/operators/HashJoinNode.h
cpp/src/cider/exec/nextgen/operators/OperatorRuntimeFunctions.h
cpp/src/cider/exec/nextgen/parsers/RelAlgEUParser.cpp
cpp/src/cider/exec/operator/join/CiderJoinHashTable.h
cpp/src/cider/exec/processor/DefaultBatchProcessor.cpp
cpp/src/cider/include/cider/CiderAllocator.h
cpp/src/cider/tests/hashtable/CiderHashTableTest.cpp
cpp/src/cider/tests/nextgen/compiler/ContextTest.cpp
cpp/src/cider/tests/nextgen/compiler/HashJoinTest.cpp
docs/develop/JoinDesign.rst

- Left Join function implement
- delete some unnecessary header files
- add related left join test
- TODO: will extract buildTableReader as a utility class and  merged with ColumnToRowReader in next PR
For NextGen HashJoin op funciton
No
UTs
INFRA

[POAE7-2812] Left Join Implement

---

cpp/src/cider/exec/operator/join/CiderChainedHashTable.cpp
cpp/src/cider/exec/operator/join/CiderChainedHashTable.h
cpp/src/cider/exec/operator/join/CiderJoinHashTable.cpp
cpp/src/cider/exec/operator/join/CiderJoinHashTable.h
cpp/src/cider/exec/operator/join/CiderLinearProbingHashTable.h
cpp/src/cider/exec/operator/join/HashFunctions.h
cpp/src/cider/exec/operator/join/HashTableUtils.h
cpp/src/cider/tests/hashtable/CiderHashTableTest.cpp

improve hashtable to support all kinds of data types in join
support all data types
No
UTs
hashjointest

[POAE7-2833] improve joinhashtable interface and add common hashfunctions

---

cpp/src/cider/exec/module/CiderOptions.cpp
cpp/src/cider/exec/nextgen/Nextgen.cpp
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.cpp
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.h
cpp/src/cider/exec/nextgen/operators/OpNode.h
cpp/src/cider/exec/nextgen/operators/ProjectNode.cpp
cpp/src/cider/exec/nextgen/operators/ProjectNode.h
cpp/src/cider/exec/nextgen/operators/RowToColumnNode.cpp
cpp/src/cider/exec/nextgen/operators/RowToColumnNode.h
cpp/src/cider/include/cider/CiderOptions.h
cpp/src/cider/tests/utils/CiderNextgenQueryRunner.cpp
cpp/src/cider/type/plan/BinaryExpr.cpp
cpp/src/cider/type/plan/BinaryExpr.h
cpp/src/cider/type/plan/ColumnExpr.cpp
cpp/src/cider/type/plan/ColumnExpr.h
cpp/src/cider/type/plan/ConstantExpr.cpp
cpp/src/cider/type/plan/ConstantExpr.h
cpp/src/cider/type/plan/Expr.cpp
cpp/src/cider/type/plan/Expr.h

cleanup FLAGS_null_separate code path
cleanup unused code
no
UT
INFRA

[POAE7-2587]cleanup FLAGS_null_separate

---

ci/scripts/build-presto-package.sh
ci/scripts/integrate-presto-bdtk.sh
ci/scripts/prepare_source_code_cicd.sh
ci/scripts/presto-bdtk-67b3bf.patch
ci/scripts/presto-integration.sh

Modified presto cider integration scripts based on new code. 
To correct the integration process. 
no
By Github Action. 
Integration & CICD

[POAE7-2889][hot fix] Modified presto integration scripts

---

cpp/src/cider-velox/benchmark/expression/ArithmeticAndComparison.cpp
cpp/src/cider-velox/benchmark/expression/PipelineOperator.cpp

benchmark support multi expressions
benchmark utils
No
benchmark
INFRA

[POAE7-2893]benchmark support multi expressions

---

cpp/src/cider/exec/nextgen/operators/VectorizedProjectNode.cpp
cpp/src/cider/tests/nextgen/compiler/NextgenCompilerTest.cpp

fix for multi-expression random core
bugfix
No
UT
INFRA

[POAE7-2900]fix multi-expression random core

---

cpp/src/cider/exec/nextgen/jitlib/base/JITValueOperations.h
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.cpp
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITEngine.h
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITUtils.h
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp
cpp/src/cider/tests/nextgen/jitlib/JITLibTest.cpp

Add bitwise logical operations in JITLib.
Support vectorized project.
No
UTs
Infra

[POAE7-2896] Bitwise Logical Operations in JITLib

---

docs/user/modules/ICL-module.rst

User guide for native parquet reader benchmark.
User guide for native parquet reader benchmark.
No
No UTs need, doc only
documentation

[POAE7-2866] User guide for native parquet reader benchmark

---

cpp/src/cider/examples/ExpressionEvalExample.cpp
docs/user/modules/expr-eval-module.rst

update expression evaluation example and doc
show expression evaluation example
No
N/A

[POAE7-2905] update expr eval example and doc

---

cpp/src/cider/tests/nextgen/functional/CiderArrayTest.cpp
cpp/src/cider/tests/utils/CiderNextgenTestBase.h
cpp/src/cider/tests/utils/DuckDbQueryRunner.cpp

1. Support Array Type in DuckDBQueryRunner
2. migrate uts
No
CiderArrayTest.cpp

[POAE7-2908] Support Array Type in DuckDBQueryRunner

---

cpp/CMakeLists.txt
cpp/src/cider-velox/benchmark/CMakeLists.txt
cpp/src/cider-velox/benchmark/expression/ArithmeticAndComparison.cpp
cpp/src/cider-velox/benchmark/expression/CMakeLists.txt
cpp/src/cider-velox/benchmark/tpch/CMakeLists.txt
cpp/src/cider-velox/benchmark/tpch/TpchFromFileBenchmark.cpp
cpp/src/cider-velox/benchmark/tpch/TpchInMemBenchmark.cpp
cpp/src/cider-velox/benchmark/tpch/TpchInMemBuilder.cpp
cpp/src/cider-velox/benchmark/tpch/TpchInMemBuilder.h

add tpch benchmark
performance profile toolkit
No
benchmark
INFRA

[POAE7-2587]add tpch benchmark

---

cpp/src/cider/exec/nextgen/Nextgen.cpp
cpp/src/cider/exec/nextgen/context/CodegenContext.h
cpp/src/cider/exec/nextgen/jitlib/base/JITControlFlow.h
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITControlFlow.cpp
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.cpp
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.h
cpp/src/cider/exec/nextgen/operators/QueryFuncInitializer.cpp
cpp/src/cider/exec/nextgen/operators/VectorizedProjectNode.cpp
cpp/src/cider/exec/nextgen/operators/VectorizedProjectNode.h
cpp/src/cider/exec/nextgen/utils/TypeUtils.h
cpp/src/cider/tests/nextgen/compiler/NextgenCompilerTest.cpp
cpp/src/cider/type/plan/BinaryExpr.cpp
cpp/src/cider/type/plan/UnaryExpr.cpp
cpp/src/cider/type/plan/UnaryExpr.h

Logical bitwise operations vectorization.
Vectorization
No
UTs
INFRA
Pls take review @Ma-Jian1 @winningsix

[POAE7-2891] Logical Operations Vectorize

---

cpp/src/cider/exec/nextgen/context/ContextRuntimeFunctions.h
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.cpp
cpp/src/cider/type/plan/BinaryExpr.cpp
cpp/src/cider/type/plan/CaseExpr.cpp

Fix case when, decimal op codegen failed.
root cause may due to log refactor, LOG(ERROR) will not longer throw exception, so ut seems passed.
fix bugs.
No
UT.

[POAE7-2903] Fix case when, decimal op codegen failed.

---

cpp/src/cider-velox/benchmark/expression/ArithmeticAndComparison.cpp
cpp/src/cider-velox/benchmark/expression/PipelineOperator.cpp
cpp/src/cider-velox/benchmark/expression/utils.h
cpp/src/cider-velox/src/CiderCrossJoinBuild.cpp
cpp/src/cider-velox/src/CiderHashJoinBuild.cpp
cpp/src/cider-velox/src/CiderPipelineOperator.cpp
cpp/src/cider/exec/module/batch/ArrowABI.h
cpp/src/cider/exec/module/batch/CiderBatchUtils.cpp
cpp/src/cider/exec/nextgen/context/Batch.cpp
cpp/src/cider/include/cider/batch/CiderBatchUtils.h
cpp/src/cider/type/plan/ColumnExpr.h

1. OutputColumnVar supports auto-vectorization
2. memory optimization for arrow array and schema
perf
No
benchmark
INFRA

[POAE7-2914]OutputColumnVar supports auto-vectorization

---

cpp/src/cider/exec/nextgen/context/CodegenContext.cpp
cpp/src/cider/exec/nextgen/context/CodegenContext.h
cpp/src/cider/exec/nextgen/operators/OperatorRuntimeFunctions.h
cpp/src/cider/exec/nextgen/operators/RowToColumnNode.cpp
cpp/src/cider/exec/nextgen/operators/RowToColumnNode.h
cpp/src/cider/exec/nextgen/operators/VectorizedProjectNode.cpp
cpp/src/cider/exec/nextgen/operators/VectorizedProjectNode.h
cpp/src/cider/tests/CMakeLists.txt
cpp/src/cider/tests/CiderBitUtilsTest.cpp
cpp/src/cider/tests/nextgen/compiler/NextgenCompilerTest.cpp
cpp/src/cider/type/plan/BinaryExpr.cpp
cpp/src/cider/type/plan/ColumnExpr.h
cpp/src/cider/type/plan/Expr.h
cpp/src/cider/type/plan/FunctionExpr.cpp
cpp/src/cider/util/CiderBitUtils.h

Comparison Operations Vectorization
Performance optimization. 
No
UTs
INFRA
Pls take a review @Ma-Jian1 @winningsix

[POAE7-2912] Comparison Operations Vectorization

---

cpp/src/cider/exec/nextgen/context/CodegenContext.h
cpp/src/cider/exec/nextgen/operators/CMakeLists.txt
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.cpp
cpp/src/cider/exec/nextgen/operators/ColumnToRowNode.h
cpp/src/cider/exec/nextgen/operators/OperatorRuntimeFunctions.h
cpp/src/cider/exec/nextgen/operators/RowToColumnNode.cpp
cpp/src/cider/exec/nextgen/operators/VectorizedFilterNode.cpp
cpp/src/cider/exec/nextgen/operators/VectorizedFilterNode.h
cpp/src/cider/exec/nextgen/operators/VectorizedProjectNode.cpp
cpp/src/cider/exec/nextgen/transformer/Transformer.cpp
cpp/src/cider/tests/CiderBitUtilsTest.cpp
cpp/src/cider/tests/substrait_plan_files/in_string_nest_with_binop.json
cpp/src/cider/util/CiderBitUtils.h

Support vectorized filter.
Performance optimization.
No
UTs
INFRA

[POAE7-2913] Vectorized Filter Support

---

cpp/src/cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cpp/src/cider/tests/substrait_plan_files/between_and_fp32_velox.json
cpp/src/cider/tests/substrait_plan_files/between_and_fp64_velox.json
cpp/src/cider/tests/substrait_plan_files/between_and_i16_velox.json
cpp/src/cider/tests/substrait_plan_files/between_and_i32_velox.json
cpp/src/cider/tests/substrait_plan_files/between_and_i64_velox.json
cpp/src/cider/tests/substrait_plan_files/between_and_i8_velox.json

Convert between...and to LE and GE for all current supported types.
Performance Optimization
No
UTs
INFRA

[POAE7-2922] Convert Between...And to BinaryOps

---

ci/scripts/presto-bdtk-67b3bf.patch
ci/scripts/presto-integration.sh
cpp/src/cider/CMakeLists.txt
cpp/src/cider/exec/nextgen/CMakeLists.txt
cpp/src/cider/exec/nextgen/function/CiderStringFunction.h
cpp/src/cider/exec/nextgen/function/CiderStringFunctions.cpp
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITFunction.cpp
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.h
cpp/src/cider/exec/nextgen/operators/VectorizedProjectNode.cpp
cpp/src/cider/exec/template/CMakeLists.txt
cpp/src/cider/function/CMakeLists.txt
cpp/src/cider/function/scalar/RuntimeFunctions.cpp
cpp/src/cider/function/scalar/RuntimeFunctions.h
cpp/src/cider/tests/nextgen/jitlib/CMakeLists.txt
cpp/src/cider/tests/nextgen/jitlib/JITLibTest.cpp
cpp/src/cider/type/data/funcannotations.h
cpp/src/cider/type/plan/CMakeLists.txt
cpp/src/cider/type/plan/UnaryExpr.cpp

- [Refactor structure of CiderStringFunctions.cpp.](https://github.com/intel/BDTK/commit/9c1f3a948eae3e02fd752ae68358960110135244)
- [Decouple runtime functions from cider_function and merge cider_type_plan with nextgen.](https://github.com/intel/BDTK/commit/fadd0945e5690d58aa75e20beecefafa29686582)
- [Optimize constant cast.](https://github.com/intel/BDTK/commit/e020189cd24cacfc02b7ed1f339bf07da5ce0c64)
Performance optimization.
No
UTs
INFRA
Pls take a review @Ma-Jian1 @yma11 @jikunshang @winningsix

[POAE7-2923] Convert String-represented Constant Date at Codegen Phase

---

cpp/src/cider/tests/utils/CMakeLists.txt
cpp/src/cider/util/CMakeLists.txt

[HotFix] Move CiderParquetReader out from cider_util.

---

cpp/src/cider-velox/test/CMakeLists.txt
cpp/src/cider/exec/processor/DefaultBatchProcessor.cpp
cpp/src/cider/tests/CMakeLists.txt
cpp/src/cider/tests/utils/CMakeLists.txt

create batchProcessor from extended expression for expression evaluator
No
public Api,cider

[POAE7-2927] expression evaluator integration

---

cpp/src/cider/common/CMakeLists.txt
cpp/src/cider/common/base/StringRef.h
cpp/src/cider/common/base/unaligned.h
cpp/src/cider/common/hashtable/Hash.h
cpp/src/cider/common/hashtable/HashTable.h
cpp/src/cider/common/hashtable/HashTableAllocator.h
cpp/src/cider/common/hashtable/StringHashMap.h
cpp/src/cider/common/hashtable/StringHashTable.h
cpp/src/cider/common/interpreters/AggregationHashTable.cpp
cpp/src/cider/common/interpreters/AggregationHashTable.h
cpp/src/cider/tests/CMakeLists.txt
cpp/src/cider/tests/CiderNewAggHashTableTest.cpp
cpp/src/cider/tests/CiderNewHashTableTest.cpp

1. Add StringHashMap and StringHashTable implementation.
2. Add String support for AggregationHashTable.
3. Add short string and long string unit tests for two suites.
Improvement.
No.
UTs.

[POAE7-2775] HashTable implementation of string

---

cpp/src/cider/exec/nextgen/function/CiderStringFunctions.cpp
cpp/src/cider/exec/plan/lookup/CMakeLists.txt
cpp/src/cider/tests/nextgen/functional/StringTest.cpp
cpp/src/cider/type/plan/Analyzer.cpp
cpp/src/cider/type/plan/Analyzer.h

add TryStringCast for date type support 
fix this issue to pass tpch q7,8,9 e2e test 
No
UT

[POAE7-2925] add TryStringCast for date type support 

---

cpp/src/cider/exec/nextgen/jitlib/base/JITValue.h
cpp/src/cider/exec/nextgen/jitlib/base/JITValueOperations.h
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.cpp
cpp/src/cider/exec/nextgen/jitlib/llvmjit/LLVMJITValue.h
cpp/src/cider/exec/nextgen/operators/VectorizedFilterNode.cpp
cpp/src/cider/exec/nextgen/operators/VectorizedProjectNode.cpp
cpp/src/cider/exec/nextgen/utils/TypeUtils.h
cpp/src/cider/exec/plan/parser/SubstraitToAnalyzerExpr.cpp
cpp/src/cider/tests/nextgen/jitlib/JITLibTest.cpp
cpp/src/cider/type/plan/BinaryExpr.cpp
cpp/src/cider/type/plan/BinaryExpr.h
cpp/src/cider/type/plan/Expr.h
cpp/src/cider/type/plan/UnaryExpr.cpp
cpp/src/cider/type/plan/UnaryExpr.h

Q6 Performance Status (In-memory TPCH SF=10)
|                                                                        | Speed-up Ratio | Time / Iter |
|:----------------------------------------------------------------------:|:--------------:|:-----------:|
|                                  Velox                                 |                |    38.52s   |
|                                  BDTK                                  |     77.71%     |    49.31s   |
| BDTK Basic Opt. (w/ constant date string opt, Between...And unfolding) |     99.84%     |    38.58s   |
|             BDTK Basic Opt. + Partial Conditions Execution             |     99.48%     |    38.72s   |
|                   BDTK Basic Opt. + Vectorized Filter                  |     97.69%     |    39.43s   |
|   BDTK …

[POAE7-2921] Enable Vectorized Filter and Project for TPC-H Q6

---

Makefile
jvm/pom.xml

Fix github security scan
Java dependency update
No
Use exist Uts
coderefactor

[POAE7-2396] bump junit and checkstyle to meet github security scan
